"""Bake the supplied Dallas Cowboys star into the existing helmet envelope (DEP-470)."""
from __future__ import annotations

import hashlib
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

SOURCE = Path(sys.argv[1]) if len(sys.argv) > 1 else Path('/Users/cwharris/Downloads/decal_svgs/cowboys_star.svg')
TARGET = Path(__file__).resolve().parents[2] / 'lib/uniforms/teams/cowboys-decal.ts'
TOKEN = re.compile(r'[A-Za-z]|[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?')

# The star's full navy envelope in the supplied 2048px viewBox is x=238..1808/y=282..1757.
# It maps to the existing Cowboys helmet placement x=296..542/y=127..371, measured from the GUD
# composite. Keeping that envelope isolates this source-art refresh from the placement decision.
SX, SY = 238.0, 282.0
TX, TY = 296.0, 127.0
SCALE_X, SCALE_Y = 246.0 / (1808.0 - 238.0), 244.0 / (1757.0 - 282.0)


def path(d: str, transform: str | None) -> str:
    nums = [float(x) for x in re.findall(r'-?(?:\d+\.?\d*|\.\d+)', transform or '')]
    ox, oy = (nums + [0, 0])[:2]
    tokens = TOKEN.findall(d)
    i = 0
    cmd = ''
    x = y = 0.0
    start = (0.0, 0.0)
    out: list[str] = []
    while i < len(tokens):
        if tokens[i].isalpha():
            cmd = tokens[i]
            i += 1
            if cmd in 'Zz':
                out.append('Z')
                x, y = start
                continue
        rel = cmd.islower()
        op = cmd.upper()
        if op in ('M', 'L'):
            x0, y0 = float(tokens[i]), float(tokens[i + 1])
            i += 2
            x, y = (x + x0, y + y0) if rel else (x0, y0)
            if op == 'M':
                start = (x, y)
            out.append(
                ('M' if op == 'M' else 'L')
                + f'{TX + (x + ox - SX) * SCALE_X:.3f},{TY + (y + oy - SY) * SCALE_Y:.3f}'
            )
            if op == 'M':
                cmd = 'l' if rel else 'L'
        elif op == 'H':
            v = float(tokens[i])
            i += 1
            x = x + v if rel else v
            out.append(f'L{TX + (x + ox - SX) * SCALE_X:.3f},{TY + (y + oy - SY) * SCALE_Y:.3f}')
        elif op == 'V':
            v = float(tokens[i])
            i += 1
            y = y + v if rel else v
            out.append(f'L{TX + (x + ox - SX) * SCALE_X:.3f},{TY + (y + oy - SY) * SCALE_Y:.3f}')
        else:
            raise ValueError(f'unsupported SVG command {cmd}')
    return ' '.join(out)


def token(fill: str) -> str:
    if fill.upper() == '#032343':
        return 'sourceNavy'
    if fill.upper() == '#FCFCFC':
        return 'sourceWhite'
    raise ValueError(f'unexpected mark color {fill}')


source = SOURCE.read_bytes()
root = ET.fromstring(source)
items: list[tuple[str, str]] = []
for element in root:
    if element.tag.rsplit('}', 1)[-1] != 'path':
        continue
    # The first path is the SVG's #FEFDFD canvas and the fourth is its #D8D8D8 right/bottom
    # export frame. Neither belongs to the helmet mark; retaining either would paint a square over
    # the shell. Every visible navy/white star path remains, in source paint order.
    if element.attrib.get('fill', '').upper() in {'#FEFDFD', '#D8D8D8'}:
        continue
    items.append((token(element.attrib['fill']), path(element.attrib['d'], element.attrib.get('transform'))))

header = (
    '// Provenance: user-supplied cowboys_star.svg (DEP-470).\n'
    f'// Source SHA-256: {hashlib.sha256(source).hexdigest()}\n'
    '// Complete navy/white star paths in original paint order. The #FEFDFD canvas and #D8D8D8\n'
    '// export frame are explicitly excluded because they are image artifacts, not helmet-mark art.\n'
    '// Placement reference: https://www.gridiron-uniforms.com/GUD/controller/controller.php?action=teams&team_id=DAL\n'
    '// Generated by scripts/uniform-draw/cowboys_decal.py; coordinates include GUD placement.\n'
    'export const COWBOYS_DECAL_PATHS = [\n'
)
TARGET.write_text(
    header + ''.join(f"  {{ fill: '{fill}', d: '{d}' }},\n" for fill, d in items) + '] as const;\n'
)
