"""Bake the supplied Giants helmet mark into the measured helmet envelope (DEP-471)."""
from __future__ import annotations

import hashlib
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

SOURCE = Path(sys.argv[1]) if len(sys.argv) > 1 else Path('/Users/cwharris/Downloads/decal_svgs/giants_modern_ny.svg')
TARGET = Path(__file__).resolve().parents[2] / 'lib/uniforms/teams/giants-decal.ts'
TOKEN = re.compile(r'[A-Za-z]|[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?')

# Existing Giants helmet placement envelope, measured from the supplied GUD composite.
TARGET_X0, TARGET_Y0, TARGET_X1, TARGET_Y1 = 319.3, 160.7, 509.6, 306.1


def path(d: str, tx: float, ty: float, sx: float, sy: float) -> str:
    tokens, i, command, x, y = TOKEN.findall(d), 0, '', 0.0, 0.0
    out: list[str] = []
    while i < len(tokens):
        if tokens[i].isalpha():
            command = tokens[i]
            i += 1
            if command in 'Zz':
                out.append('Z')
                continue
        relative = command.islower()
        op = command.upper()
        if op in ('M', 'L'):
            nx, ny = float(tokens[i]), float(tokens[i + 1]); i += 2
            x, y = (x + nx, y + ny) if relative else (nx, ny)
            out.append(('M' if op == 'M' and (not out or out[-1] == 'Z') else 'L') + f'{TARGET_X0 + (x + tx - sx) * (TARGET_X1 - TARGET_X0) / (source_x1 - source_x0):.3f},{TARGET_Y0 + (y + ty - sy) * (TARGET_Y1 - TARGET_Y0) / (source_y1 - source_y0):.3f}')
            if op == 'M': command = 'l' if relative else 'L'
        elif op in ('H', 'V'):
            value = float(tokens[i]); i += 1
            if op == 'H': x = x + value if relative else value
            else: y = y + value if relative else value
            out.append(f'L{TARGET_X0 + (x + tx - sx) * (TARGET_X1 - TARGET_X0) / (source_x1 - source_x0):.3f},{TARGET_Y0 + (y + ty - sy) * (TARGET_Y1 - TARGET_Y0) / (source_y1 - source_y0):.3f}')
        else:
            raise ValueError(f'unsupported SVG command {command!r}')
    return ' '.join(out)


source = SOURCE.read_bytes()
root = ET.fromstring(source)
elements = [e for e in root if e.tag.rsplit('}', 1)[-1] == 'path']
if len(elements) != 2:
    raise ValueError(f'expected two modern NY paths, found {len(elements)}')

source_x0, source_y0, source_x1, source_y1 = 729.0, 13.0, 1800.0, 562.0
paths = []
for element in elements:
    match = re.fullmatch(r'translate\(([-+\d.]+),([-+\d.]+)\)', element.attrib.get('transform', ''))
    if not match:
        raise ValueError(f"unsupported transform {element.attrib.get('transform')!r}")
    paths.append(path(element.attrib['d'], float(match.group(1)), float(match.group(2)), source_x0, source_y0))

# Normalize the union to the measured helmet envelope. The source SVG has a generous canvas and
# translated paths, so its visible coordinates are intentionally fitted after parsing.
points = [(float(x), float(y)) for d in paths for pair in re.findall(r'[-\d.]+,[-\d.]+', d) for x, y in [pair.split(',')]]
min_x, max_x = min(x for x, _ in points), max(x for x, _ in points)
min_y, max_y = min(y for _, y in points), max(y for _, y in points)
def normalize(d: str) -> str:
    def replace(match: re.Match[str]) -> str:
        x, y = map(float, match.group(1).split(','))
        nx = TARGET_X0 + (x - min_x) * (TARGET_X1 - TARGET_X0) / (max_x - min_x)
        ny = TARGET_Y0 + (y - min_y) * (TARGET_Y1 - TARGET_Y0) / (max_y - min_y)
        return f'{nx:.3f},{ny:.3f}'
    return re.sub(r'([-\d.]+,[-\d.]+)', replace, d)
paths = [normalize(d) for d in paths]

header = f"""// Provenance: user-supplied giants_modern_ny.svg (DEP-471).
// Source SHA-256: {hashlib.sha256(source).hexdigest()}
// Both source paths are recolored fully white; transparent background is preserved.
// Placement reference: https://www.gridiron-uniforms.com/GUD/controller/controller.php?action=teams&team_id=NYG
// Generated by scripts/uniform-draw/giants_decal.py; coordinates include placement.
export const GIANTS_DECAL_MODERN_PATHS = [
"""
TARGET.write_text(header + ''.join(f"  {{ fill: 'white', d: '{d}' }},\n" for d in paths) + "] as const;\n")
