"""Bake Cooper's 2026_Jacksonville.svg paths directly into the Jaguars decal (DEP-464).

Usage: python3 scripts/uniform-draw/jaguars_decal.py /path/to/2026_Jacksonville.svg
No tracing, simplification, or recoloring: retain paint order and every logo path.
Only source paths 0, 5, 6 (the page background and right/bottom border) are excluded.
GUD's 2025 JAX composite supplies placement only: shell x60..149/y26..113,
mark x78..123/y43..76. Transfer to the renderer's raw shell x139..702/y65..637,
preserving the supplied mark's aspect. The throwback uses different historical art.
"""

import hashlib
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


def bake(element):
    # The supplied file uses only relative polygon commands and per-path translations.
    tx, *rest = map(float, re.findall(r'-?\d+(?:\.\d+)?', element.attrib['transform']))
    ty = rest[0] if rest else 0
    tokens = re.findall(r'[mlhvz]|-?\d+(?:\.\d+)?', element.attrib['d'])
    x = y = sx = sy = 0
    out = []
    i = 0
    command = None
    while i < len(tokens):
        if tokens[i].isalpha():
            command = tokens[i]
            i += 1
        if command == 'z':
            out.append('Z')
            x, y = sx, sy
            continue
        if command in ('m', 'l'):
            x += float(tokens[i])
            y += float(tokens[i + 1])
            i += 2
        elif command == 'h':
            x += float(tokens[i])
            i += 1
        elif command == 'v':
            y += float(tokens[i])
            i += 1
        else:
            raise ValueError(f'Unsupported command: {command}')
        move = command == 'm'
        if move:
            sx, sy = x, y
            command = 'l'
        # Source art bounds are x247..1805/y443..1610. Width 285 raw helmet units.
        px = 253 + (x + tx - 247) * 285 / 1558
        py = 177 + (y + ty - 443) * 285 / 1558
        out.append(f'{"M" if move else "L"}{px:.3f},{py:.3f}')
    return ' '.join(out)


source = Path(sys.argv[1]).read_bytes()
root = ET.fromstring(source)
target = Path(__file__).resolve().parents[2] / 'lib/uniforms/teams/jaguars.ts'
text = target.read_text()
start = text.index('// Provenance:')
end = text.index('// The sleeve bands', start)
header = (
    '// Provenance: user-supplied 2026_Jacksonville.svg (DEP-464), club trademark/non-free art.\n'
    f'// Source SHA-256: {hashlib.sha256(source).hexdigest()}\n'
    '// Direct vector paths and original colors; only the canvas/background border is omitted.\n'
    '// Placement only: https://www.gridiron-uniforms.com/GUD/controller/controller.php?'
    'action=teams-season&team_id=JAX&year=2025\n'
    '// Generated by scripts/uniform-draw/jaguars_decal.py; coordinates include placement.\n'
    'export const JAGUARS_DECAL_PATHS = [\n'
)
paths = ''.join(
    f"  {{ fill: '{element.attrib['fill']}', d: '{bake(element)}' }},\n"
    for index, element in enumerate(root) if index not in (0, 5, 6)
)
target.write_text(text[:start] + header + paths + '] as const;\n\n' + text[end:])
