"""Bake the supplied Detroit Lions mark into helmet-space paths (DEP-475)."""
from __future__ import annotations

import hashlib
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

SOURCE = Path(sys.argv[1]) if len(sys.argv) > 1 else Path('/Users/cwharris/Downloads/decal_svgs/lions_leaping_lion.svg')
TARGET = Path(__file__).resolve().parents[2] / 'lib/uniforms/teams/lions-decal.ts'
TOKEN = re.compile(r'[A-Za-z]|[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?')

# The supplied art's visible mark is x=252..1797/y=432..1611 in its 2048 viewBox.
# Fit that measured envelope to the existing Lions helmet envelope x=189..578/y=122..419.
SX, SY, SCALE = 252.0, 432.0, 389.0 / (1797.0 - 252.0)
TX, TY = 189.0, 122.0

def path(d: str, transform: str | None) -> str:
    nums = [float(x) for x in re.findall(r'-?(?:\d+\.?\d*|\.\d+)', transform or '')]
    ox, oy = (nums + [0, 0])[:2]
    tokens = TOKEN.findall(d); i = 0; cmd = ''; x = y = 0.0; start = (0.0, 0.0); out = []
    while i < len(tokens):
        if tokens[i].isalpha():
            cmd = tokens[i]; i += 1
            if cmd in 'Zz': out.append('Z'); x, y = start; continue
        rel = cmd.islower(); op = cmd.upper()
        if op in ('M', 'L'):
            x0, y0 = float(tokens[i]), float(tokens[i + 1]); i += 2
            x, y = (x + x0, y + y0) if rel else (x0, y0)
            if op == 'M': start = (x, y)
            out.append(('M' if op == 'M' else 'L') + f'{TX + (x + ox - SX) * SCALE:.3f},{TY + (y + oy - SY) * SCALE:.3f}')
            if op == 'M': cmd = 'l' if rel else 'L'
        elif op == 'H':
            v = float(tokens[i]); i += 1; x = x + v if rel else v
            out.append(f'L{TX + (x + ox - SX) * SCALE:.3f},{TY + (y + oy - SY) * SCALE:.3f}')
        elif op == 'V':
            v = float(tokens[i]); i += 1; y = y + v if rel else v
            out.append(f'L{TX + (x + ox - SX) * SCALE:.3f},{TY + (y + oy - SY) * SCALE:.3f}')
        else: raise ValueError(f'unsupported SVG command {cmd}')
    return ' '.join(out)

source = SOURCE.read_bytes(); root = ET.fromstring(source)
items = []
for element in root:
    if element.tag.rsplit('}', 1)[-1] != 'path':
        continue
    # These source paths draw the 2048px canvas and its right/bottom border artifacts.
    if element.attrib.get('transform') in {'translate(0)', 'translate(2008)', 'translate(2047,1)'}:
        continue
    items.append((element.attrib['fill'], path(element.attrib['d'], element.attrib.get('transform'))))
header = ("// Provenance: user-supplied lions_leaping_lion.svg (DEP-475), club trademark/non-free art.\n"
          f"// Source SHA-256: {hashlib.sha256(source).hexdigest()}\n"
          "// Direct source paths in original paint order; canvas and border paths are omitted.\n"
          "// Placement reference: https://www.gridiron-uniforms.com/GUD/controller/controller.php?action=teams&team_id=DET\n"
          "// Generated by scripts/uniform-draw/lions_decal.py; coordinates include placement.\n"
          "export const LIONS_DECAL_PATHS = [\n")
def token(fill: str) -> str:
    if fill.upper() in {'#0276B6', '#0076B6'}: return 'blue'
    if fill.upper().startswith('#F'): return 'white'
    return 'silver'

TARGET.write_text(header + ''.join(f"  {{ fill: '{token(fill)}', d: '{d}' }},\n" for fill, d in items) + "] as const;\n")
