-- AUTO-GENERATED by scripts/gen-uniform-seed.mts from lib/uniforms/data.ts.
-- Do not edit by hand. Regenerate after changing the curated archive.
-- Idempotent, source-guarded: only rewrites source='curated' rows, never espn home rows.

insert into uniforms (id, team_id, kind, name, source, year_start, year_end, is_current, color_primary, color_secondary, color_accent, ui_accent, on_accent, image_path)
values
  ('seahawks-1976-throwback', 'seahawks', 'throwback', '1976 Throwback', 'curated', 1976, 2001, false, '#003087', '#046A38', '#8A8D8F', '#3DB06A', '#0a0e1a', NULL),
  ('buccaneers-creamsicle', 'buccaneers', 'throwback', 'Creamsicle', 'curated', 1976, 1996, true, '#FF8200', '#C8102E', '#FFFFFF', '#FF8200', '#0a0e1a', NULL),
  ('eagles-kelly-green', 'eagles', 'throwback', 'Kelly Green', 'curated', 1987, 1995, true, '#046A38', '#A5ACAF', '#FFFFFF', '#2BB673', '#0a0e1a', NULL),
  ('broncos-orange-crush', 'broncos', 'throwback', 'Orange Crush', 'curated', 1968, 1996, false, '#001489', '#FA4616', '#FFFFFF', '#FA4616', '#0a0e1a', NULL),
  ('seahawks-away', 'seahawks', 'away', 'Away', 'curated', NULL, NULL, true, '#FFFFFF', '#002244', '#69BE28', '#69BE28', '#0a0e1a', NULL),
  ('bills-away', 'bills', 'away', 'Away', 'curated', NULL, NULL, true, '#FFFFFF', '#00338D', '#C60C30', '#5B9BFF', '#0a0e1a', NULL),
  ('dolphins-away', 'dolphins', 'away', 'Away', 'curated', NULL, NULL, true, '#FFFFFF', '#008E97', '#FC4C02', '#2DD4D4', '#0a0e1a', NULL),
  ('patriots-away', 'patriots', 'away', 'Away', 'curated', NULL, NULL, true, '#FFFFFF', '#002244', '#C60C30', '#C8CDD6', '#0a0e1a', NULL),
  ('jets-away', 'jets', 'away', 'Away', 'curated', NULL, NULL, true, '#FFFFFF', '#125740', '#125740', '#4CC38A', '#0a0e1a', NULL),
  ('cardinals-away', 'cardinals', 'away', 'Away', 'curated', NULL, NULL, true, '#FFFFFF', '#97233F', '#FFB612', '#FF4D6A', '#0a0e1a', NULL),
  ('rams-away', 'rams', 'away', 'Away', 'curated', NULL, NULL, true, '#FFFFFF', '#003594', '#FFA300', '#FFC20E', '#0a0e1a', NULL),
  ('49ers-away', '49ers', 'away', 'Away', 'curated', NULL, NULL, true, '#FFFFFF', '#AA0000', '#B3995D', '#FF4D4D', '#0a0e1a', NULL)
on conflict (id) do update set
  team_id = excluded.team_id,
  kind = excluded.kind,
  name = excluded.name,
  year_start = excluded.year_start,
  year_end = excluded.year_end,
  is_current = excluded.is_current,
  color_primary = excluded.color_primary,
  color_secondary = excluded.color_secondary,
  color_accent = excluded.color_accent,
  ui_accent = excluded.ui_accent,
  on_accent = excluded.on_accent,
  image_path = excluded.image_path,
  updated_at = now()
where uniforms.source = 'curated';
