-- nflverse Layer-1 source tables (full box score), one typed table per source grain.
-- Part of the full-stat-surface design (vault 2026-09-11-nflverse-full-stat-surface-design,
-- ticket DEP-541): sources are separate in, the app reads only the canonical layer.
-- Columns are generated verbatim from the release headers (all stat fields kept;
-- lists like fg_made_list stay text for the raw layer, parsed during consolidation).
-- The source's own player_id/season/week/season_type become our identity columns
-- (source_player_id + our ESPN player_id, nullable for a crosswalk miss -- the row
-- still lands rather than being dropped).

create table nflverse_player_season (
  source_player_id text not null,
  player_id text,
  season smallint not null,
  season_type text not null default 'REG',
  updated_at timestamptz not null default now(),
  player_name text,
  player_display_name text,
  position text,
  position_group text,
  headshot_url text,
  recent_team text,
  games numeric,
  completions numeric,
  attempts numeric,
  passing_yards numeric,
  passing_tds numeric,
  passing_interceptions numeric,
  sacks_suffered numeric,
  sack_yards_lost numeric,
  sack_fumbles numeric,
  sack_fumbles_lost numeric,
  passing_air_yards numeric,
  passing_yards_after_catch numeric,
  passing_first_downs numeric,
  passing_epa numeric,
  passing_cpoe numeric,
  passing_2pt_conversions numeric,
  pacr numeric,
  passing_10 numeric,
  passing_16 numeric,
  passing_20 numeric,
  passing_40 numeric,
  carries numeric,
  rushing_yards numeric,
  rushing_tds numeric,
  rushing_fumbles numeric,
  rushing_fumbles_lost numeric,
  rushing_first_downs numeric,
  rushing_epa numeric,
  rushing_2pt_conversions numeric,
  rushing_10 numeric,
  rushing_12 numeric,
  rushing_20 numeric,
  rushing_40 numeric,
  receptions numeric,
  targets numeric,
  receiving_yards numeric,
  receiving_tds numeric,
  receiving_fumbles numeric,
  receiving_fumbles_lost numeric,
  receiving_air_yards numeric,
  receiving_yards_after_catch numeric,
  receiving_first_downs numeric,
  receiving_epa numeric,
  receiving_2pt_conversions numeric,
  receiving_10 numeric,
  receiving_16 numeric,
  receiving_20 numeric,
  receiving_40 numeric,
  racr numeric,
  target_share numeric,
  air_yards_share numeric,
  wopr numeric,
  special_teams_tds numeric,
  def_tackles_solo numeric,
  def_tackles_with_assist numeric,
  def_tackle_assists numeric,
  def_tackles_for_loss numeric,
  def_tackles_for_loss_yards numeric,
  def_fumbles_forced numeric,
  def_sacks numeric,
  def_sack_yards numeric,
  def_qb_hits numeric,
  def_interceptions numeric,
  def_interception_yards numeric,
  def_pass_defended numeric,
  def_tds numeric,
  def_fumbles numeric,
  def_safeties numeric,
  def_punt_blocks numeric,
  def_pat_blocks numeric,
  def_fg_blocks numeric,
  def_2pt_atts numeric,
  def_2pt_made numeric,
  misc_yards numeric,
  fumble_recovery_own numeric,
  fumble_recovery_yards_own numeric,
  fumble_recovery_opp numeric,
  fumble_recovery_yards_opp numeric,
  fumble_recovery_tds numeric,
  penalties numeric,
  penalty_yards numeric,
  fumbles_forced_by_opp numeric,
  fumbles_not_forced numeric,
  fumbles_out_of_bounds numeric,
  fumbles_total numeric,
  fumbles_lost_total numeric,
  punt_returns numeric,
  punt_return_yards numeric,
  kickoff_returns numeric,
  kickoff_return_yards numeric,
  fg_made numeric,
  fg_att numeric,
  fg_missed numeric,
  fg_blocked numeric,
  fg_long numeric,
  fg_pct numeric,
  fg_made_0_19 numeric,
  fg_made_20_29 numeric,
  fg_made_30_39 numeric,
  fg_made_40_49 numeric,
  fg_made_50_59 numeric,
  fg_made_60_ numeric,
  fg_missed_0_19 numeric,
  fg_missed_20_29 numeric,
  fg_missed_30_39 numeric,
  fg_missed_40_49 numeric,
  fg_missed_50_59 numeric,
  fg_missed_60_ numeric,
  fg_made_list text,
  fg_missed_list text,
  fg_blocked_list text,
  fg_made_distance text,
  fg_missed_distance text,
  fg_blocked_distance text,
  pat_made numeric,
  pat_att numeric,
  pat_missed numeric,
  pat_blocked numeric,
  pat_pct numeric,
  gwfg_made numeric,
  gwfg_att numeric,
  gwfg_missed numeric,
  gwfg_blocked numeric,
  gwfg_distance_list text,
  pt_att numeric,
  pt_blocked numeric,
  pt_long numeric,
  pt_yards numeric,
  pt_inside_20 numeric,
  pt_out_of_bounds numeric,
  pt_downed numeric,
  pt_touchback numeric,
  pt_fair_caught numeric,
  pt_returned numeric,
  pt_return_yards numeric,
  pt_return_tds numeric,
  pt_net_yards numeric,
  fantasy_points numeric,
  fantasy_points_ppr numeric,
  primary key (source_player_id, season, season_type)
);
create index nflverse_player_season_player_id_idx on nflverse_player_season(player_id);
grant select, insert, update, delete on nflverse_player_season to anon, authenticated, service_role;
alter table nflverse_player_season enable row level security;
create policy "public read" on nflverse_player_season for select to anon, authenticated using (true);

create table nflverse_player_week (
  source_player_id text not null,
  player_id text,
  season smallint not null,
  season_type text not null default 'REG',
  week smallint,
  updated_at timestamptz not null default now(),
  player_name text,
  player_display_name text,
  position text,
  position_group text,
  headshot_url text,
  game_id text,
  team text,
  opponent_team text,
  completions numeric,
  attempts numeric,
  passing_yards numeric,
  passing_tds numeric,
  passing_interceptions numeric,
  sacks_suffered numeric,
  sack_yards_lost numeric,
  sack_fumbles numeric,
  sack_fumbles_lost numeric,
  passing_air_yards numeric,
  passing_yards_after_catch numeric,
  passing_first_downs numeric,
  passing_epa numeric,
  passing_cpoe numeric,
  passing_2pt_conversions numeric,
  pacr numeric,
  passing_10 numeric,
  passing_16 numeric,
  passing_20 numeric,
  passing_40 numeric,
  carries numeric,
  rushing_yards numeric,
  rushing_tds numeric,
  rushing_fumbles numeric,
  rushing_fumbles_lost numeric,
  rushing_first_downs numeric,
  rushing_epa numeric,
  rushing_2pt_conversions numeric,
  rushing_10 numeric,
  rushing_12 numeric,
  rushing_20 numeric,
  rushing_40 numeric,
  receptions numeric,
  targets numeric,
  receiving_yards numeric,
  receiving_tds numeric,
  receiving_fumbles numeric,
  receiving_fumbles_lost numeric,
  receiving_air_yards numeric,
  receiving_yards_after_catch numeric,
  receiving_first_downs numeric,
  receiving_epa numeric,
  receiving_2pt_conversions numeric,
  receiving_10 numeric,
  receiving_16 numeric,
  receiving_20 numeric,
  receiving_40 numeric,
  racr numeric,
  target_share numeric,
  air_yards_share numeric,
  wopr numeric,
  special_teams_tds numeric,
  def_tackles_solo numeric,
  def_tackles_with_assist numeric,
  def_tackle_assists numeric,
  def_tackles_for_loss numeric,
  def_tackles_for_loss_yards numeric,
  def_fumbles_forced numeric,
  def_sacks numeric,
  def_sack_yards numeric,
  def_qb_hits numeric,
  def_interceptions numeric,
  def_interception_yards numeric,
  def_pass_defended numeric,
  def_tds numeric,
  def_fumbles numeric,
  def_safeties numeric,
  def_punt_blocks numeric,
  def_pat_blocks numeric,
  def_fg_blocks numeric,
  def_2pt_atts numeric,
  def_2pt_made numeric,
  misc_yards numeric,
  fumble_recovery_own numeric,
  fumble_recovery_yards_own numeric,
  fumble_recovery_opp numeric,
  fumble_recovery_yards_opp numeric,
  fumble_recovery_tds numeric,
  penalties numeric,
  penalty_yards numeric,
  fumbles_forced_by_opp numeric,
  fumbles_not_forced numeric,
  fumbles_out_of_bounds numeric,
  fumbles_total numeric,
  fumbles_lost_total numeric,
  punt_returns numeric,
  punt_return_yards numeric,
  kickoff_returns numeric,
  kickoff_return_yards numeric,
  fg_made numeric,
  fg_att numeric,
  fg_missed numeric,
  fg_blocked numeric,
  fg_long numeric,
  fg_pct numeric,
  fg_made_0_19 numeric,
  fg_made_20_29 numeric,
  fg_made_30_39 numeric,
  fg_made_40_49 numeric,
  fg_made_50_59 numeric,
  fg_made_60_ numeric,
  fg_missed_0_19 numeric,
  fg_missed_20_29 numeric,
  fg_missed_30_39 numeric,
  fg_missed_40_49 numeric,
  fg_missed_50_59 numeric,
  fg_missed_60_ numeric,
  fg_made_list text,
  fg_missed_list text,
  fg_blocked_list text,
  fg_made_distance text,
  fg_missed_distance text,
  fg_blocked_distance text,
  pat_made numeric,
  pat_att numeric,
  pat_missed numeric,
  pat_blocked numeric,
  pat_pct numeric,
  gwfg_made numeric,
  gwfg_att numeric,
  gwfg_missed numeric,
  gwfg_blocked numeric,
  gwfg_distance text,
  pt_att numeric,
  pt_blocked numeric,
  pt_long numeric,
  pt_yards numeric,
  pt_inside_20 numeric,
  pt_out_of_bounds numeric,
  pt_downed numeric,
  pt_touchback numeric,
  pt_fair_caught numeric,
  pt_returned numeric,
  pt_return_yards numeric,
  pt_return_tds numeric,
  pt_net_yards numeric,
  fantasy_points numeric,
  fantasy_points_ppr numeric,
  primary key (source_player_id, season, season_type, week)
);
create index nflverse_player_week_player_id_idx on nflverse_player_week(player_id);
grant select, insert, update, delete on nflverse_player_week to anon, authenticated, service_role;
alter table nflverse_player_week enable row level security;
create policy "public read" on nflverse_player_week for select to anon, authenticated using (true);
