// Serializes resolved TeamRosters into a Postgres seed script (supabase/seed.sql) so a
// local `supabase db reset` restores the ESPN-ingested data without re-running the live
// ingest (scripts/ingest-espn.mts SEED_OUT mode calls this). Column lists mirror
// writeTeam()/writeTeamStats() in that script — keep them in sync; this is the offline
// twin of those upserts. Every statement is `on conflict … do nothing` and safe to
// re-run, except `teams`: 20260707190000_seed_teams.sql pre-seeds a bare identity row
// per team for FK purposes, so teams uses `do update set` to overwrite that stub with
// the real ESPN data instead of silently no-oping.
import { toDepthChartRows } from './transform';
import type { Coach } from './transform';
import type { TeamRoster, TeamStats } from '../types';
// Escaping/serialization lives in lib/seed-sql.ts, shared with lib/nflverse/seed-sql.ts.
import { insertStatement, type Val } from '@/lib/utils/seed-sql';
import { tables } from '@/lib/supabase/tables';

export interface SeedEntry {
  roster: TeamRoster;
  coach: Coach | null;
  stats: TeamStats[];
}

// Build the full seed script from resolved rosters. FK order: teams -> players ->
// depth_chart_entries + special_teams_slots -> team_stats. updated_at is omitted so the
// column default (now()) fills it and regenerated seeds don't churn the diff with
// timestamps.
export function buildSeedSql(entries: SeedEntry[]): string {
  const teams: Record<string, Val>[] = [];
  const brandColors: Record<string, Val>[] = [];
  const players: Record<string, Val>[] = [];
  const depth: Record<string, Val>[] = [];
  const special: Record<string, Val>[] = [];
  const teamStats: Record<string, Val>[] = [];

  for (const { roster, coach, stats } of entries) {
    const { team, players: roosterPlayers, specialTeams } = roster;
    teams.push({
      id: team.id,
      espn_id: null,
      abbrev: team.abbrev,
      city: team.city,
      name: team.name,
      conference: team.conference,
      division: team.division,
      logo_url: team.logo ?? null,
      logo_dark_url: team.logoDark ?? null,
      coach_name: coach?.name ?? null,
      coach_espn_id: coach?.espnId ?? null,
      coach_experience: coach?.experience ?? null,
    });
    brandColors.push({
      team_id: team.id,
      color_primary: team.colors.primary,
      color_secondary: team.colors.secondary,
      color_accent: team.colors.accent,
      ui_accent: team.colors.uiAccent,
      on_accent: team.colors.onAccent,
    });

    for (const p of roosterPlayers) {
      players.push({
        id: p.id,
        team_id: team.id,
        name: p.name,
        number: p.number,
        position: p.position,
        status: p.status,
        age: p.age,
        college: p.college,
        experience: p.experience,
        height: p.height,
        weight: p.weight,
        bio: p.bio,
        photo_url: p.photoUrl ?? null,
      });
    }

    for (const row of toDepthChartRows(roosterPlayers)) {
      depth.push({
        team_id: team.id,
        position: row.position,
        depth_rank: row.depthRank,
        player_id: row.playerId,
      });
    }

    for (const s of specialTeams) {
      special.push({
        id: `${team.id}-${s.id}`,
        team_id: team.id,
        label: s.label,
        player_id: s.playerId,
        x: s.x,
        y: s.y,
      });
    }

    // playoff_seed only, mirroring writeTeamStats' narrowed live upsert after the DEP-146
    // re-own -- the record columns are nflverse's now (buildTeamRecordsSeedSql).
    for (const s of stats) {
      teamStats.push({
        team_id: team.id,
        season: s.season,
        playoff_seed: s.playoffSeed,
      });
    }
  }

  const parts = [
    '-- Generated by `npm run gen:espn-seed` (scripts/ingest-espn.mts SEED_OUT mode).',
    '-- ESPN roster snapshot for local `supabase db reset`. Do not hand-edit; regenerate.',
    '',
    insertStatement(
      tables.teams,
      [
        'id',
        'espn_id',
        'abbrev',
        'city',
        'name',
        'conference',
        'division',
        'logo_url',
        'logo_dark_url',
        'coach_name',
        'coach_espn_id',
        'coach_experience',
      ],
      teams,
      'id',
      [
        'espn_id',
        'abbrev',
        'city',
        'name',
        'conference',
        'division',
        'logo_url',
        'logo_dark_url',
        'coach_name',
        'coach_espn_id',
        'coach_experience',
      ]
    ),
    insertStatement(
      tables.brandColors,
      ['team_id', 'color_primary', 'color_secondary', 'color_accent', 'ui_accent', 'on_accent'],
      brandColors,
      'team_id',
      ['color_primary', 'color_secondary', 'color_accent', 'ui_accent', 'on_accent']
    ),
    insertStatement(
      tables.players,
      [
        'id',
        'team_id',
        'name',
        'number',
        'position',
        'status',
        'age',
        'college',
        'experience',
        'height',
        'weight',
        'bio',
        'photo_url',
      ],
      players,
      'id'
    ),
    insertStatement(
      tables.depthChartEntries,
      ['team_id', 'position', 'depth_rank', 'player_id'],
      depth,
      'team_id,position,depth_rank'
    ),
    insertStatement(
      tables.specialTeamsSlots,
      ['id', 'team_id', 'label', 'player_id', 'x', 'y'],
      special,
      'id'
    ),
    insertStatement(
      tables.teamStats,
      ['team_id', 'season', 'playoff_seed'],
      teamStats,
      'team_id,season'
    ),
  ];

  return parts.filter(Boolean).join('\n') + '\n';
}
