// Serializes resolved TeamRosters into a Postgres seed script (supabase/seed.sql) so a
// local `supabase db reset` restores the ESPN-ingested data without re-running the live
// ingest (scripts/ingest-espn.mts SEED_OUT mode calls this). Column lists mirror
// writeTeam() in that script — keep them in sync; this is the offline twin of those
// upserts. Every statement is `on conflict … do nothing`, so it composes with the
// migration-seeded teams/uniforms and is safe to re-run.
import { toDepthChartRows } from './transform';
import type { TeamRoster } from '../types';

type Val = string | number | boolean | null | undefined;

// SQL literal for a single value. Strings are single-quote-escaped; null/undefined ->
// NULL. Untrusted ESPN text (names with apostrophes) must never break the script.
export function sqlValue(v: Val): string {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  return `'${v.replace(/'/g, "''")}'`;
}

// One multi-row INSERT ... ON CONFLICT DO NOTHING for a table. Empty rows -> ''.
export function insertStatement(
  table: string,
  columns: string[],
  rows: Record<string, Val>[],
  conflict: string
): string {
  if (rows.length === 0) return '';
  const values = rows
    .map((r) => `  (${columns.map((c) => sqlValue(r[c])).join(', ')})`)
    .join(',\n');
  return `insert into ${table} (${columns.join(', ')}) values\n${values}\non conflict (${conflict}) do nothing;\n`;
}

// Build the full seed script from resolved rosters. FK order: teams -> players ->
// depth_chart_entries + special_teams_slots. updated_at is omitted so the column default
// (now()) fills it and regenerated seeds don't churn the diff with timestamps.
export function buildSeedSql(rosters: TeamRoster[]): string {
  const teams: Record<string, Val>[] = [];
  const players: Record<string, Val>[] = [];
  const depth: Record<string, Val>[] = [];
  const special: Record<string, Val>[] = [];

  for (const { team, players: roster, specialTeams } of rosters) {
    teams.push({
      id: team.id,
      espn_id: null,
      abbrev: team.abbrev,
      city: team.city,
      name: team.name,
      conference: team.conference,
      division: team.division,
      color_primary: team.colors.primary,
      color_secondary: team.colors.secondary,
      color_accent: team.colors.accent,
      ui_accent: team.colors.uiAccent,
      on_accent: team.colors.onAccent,
      logo_url: team.logo ?? null,
      logo_dark_url: team.logoDark ?? null,
      coach_name: team.coach?.name ?? null,
      coach_experience: team.coach?.experience ?? null,
    });

    for (const p of roster) {
      players.push({
        id: p.id,
        team_id: team.id,
        name: p.name,
        number: p.number,
        position: p.position,
        status: p.status,
        age: p.age,
        college: p.college,
        experience: p.experience,
        height: p.height,
        weight: p.weight,
        bio: p.bio,
        photo_url: p.photoUrl ?? null,
      });
    }

    for (const row of toDepthChartRows(roster)) {
      depth.push({
        team_id: team.id,
        position: row.position,
        depth_rank: row.depthRank,
        player_id: row.playerId,
      });
    }

    for (const s of specialTeams) {
      special.push({
        id: `${team.id}-${s.id}`,
        team_id: team.id,
        label: s.label,
        player_id: s.playerId,
        x: s.x,
        y: s.y,
      });
    }
  }

  const parts = [
    '-- Generated by `npm run gen:espn-seed` (scripts/ingest-espn.mts SEED_OUT mode).',
    '-- ESPN roster snapshot for local `supabase db reset`. Do not hand-edit; regenerate.',
    '',
    insertStatement(
      'teams',
      [
        'id',
        'espn_id',
        'abbrev',
        'city',
        'name',
        'conference',
        'division',
        'color_primary',
        'color_secondary',
        'color_accent',
        'ui_accent',
        'on_accent',
        'logo_url',
        'logo_dark_url',
        'coach_name',
        'coach_experience',
      ],
      teams,
      'id'
    ),
    insertStatement(
      'players',
      [
        'id',
        'team_id',
        'name',
        'number',
        'position',
        'status',
        'age',
        'college',
        'experience',
        'height',
        'weight',
        'bio',
        'photo_url',
      ],
      players,
      'id'
    ),
    insertStatement(
      'depth_chart_entries',
      ['team_id', 'position', 'depth_rank', 'player_id'],
      depth,
      'team_id,position,depth_rank'
    ),
    insertStatement(
      'special_teams_slots',
      ['id', 'team_id', 'label', 'player_id', 'x', 'y'],
      special,
      'id'
    ),
  ];

  return parts.filter(Boolean).join('\n') + '\n';
}
