import { UNIFORMS } from './data';
import { uniformArtURL } from './art';

// Turns the hand-curated archive (data.ts) into an idempotent SQL seed migration. Every
// uniform is curated, so the upsert owns every emitted row and has no provenance branch.

const COLUMNS = [
  'id',
  'team_id',
  'kind',
  'name',
  'year_start',
  'year_end',
  'is_current',
  'color_primary',
  'color_secondary',
  'color_accent',
  'ui_accent',
  'on_accent',
  'image_path',
] as const;

// Columns refreshed on conflict — everything except the stable id key. updated_at is set
// to now() so a reseed reflects freshness.
const UPDATE_COLS = COLUMNS.filter((c) => c !== 'id');

function sqlStr(v: string): string {
  return `'${v.replace(/'/g, "''")}'`;
}

function sqlVal(v: string | number | boolean | null): string {
  if (v === null) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  return sqlStr(v);
}

function rowValues(u: (typeof UNIFORMS)[number]): string {
  const id = `${u.teamId}-${u.slug}-${u.yearStart}`;
  const record: Record<string, string | number | boolean | null> = {
    id,
    team_id: u.teamId,
    kind: u.kind,
    name: u.name,
    year_start: u.yearStart,
    year_end: u.yearEnd,
    is_current: u.isCurrent,
    color_primary: u.colors.primary,
    color_secondary: u.colors.secondary,
    color_accent: u.colors.accent,
    ui_accent: u.colors.uiAccent,
    on_accent: u.colors.onAccent,
    // Deterministic artifact URL (DEP-220): every curated kit's thumb lives at
    // UNIFORM_ART_BASE_URL/<teamId>-<slug>-<yearStart>.webp. data.ts's explicit imagePath override
    // (if ever set) wins over the derived default.
    image_path: u.imagePath ?? uniformArtURL(id),
  };
  return `  (${COLUMNS.map((c) => sqlVal(record[c])).join(', ')})`;
}

export function generateCuratedSeedSql(): string {
  const values = UNIFORMS.map(rowValues).join(',\n');
  const updates = UPDATE_COLS.map((c) => `${c} = excluded.${c}`).join(',\n  ');
  return `-- AUTO-GENERATED by scripts/gen-uniform-seed.mts from lib/uniforms/data.ts.
-- Do not edit by hand. Regenerate after changing the curated archive.
-- Idempotent: every emitted row is curated jersey truth.

insert into uniforms (${COLUMNS.join(', ')})
values
${values}
on conflict (id) do update set
  ${updates},
  updated_at = now();
`;
}
