import { UNIFORMS } from './data';

// Turns the hand-curated archive (data.ts) into an append-only SQL seed migration. The
// emitted upsert is idempotent (ON CONFLICT (id) DO UPDATE) and guarded by
// `WHERE uniforms.source = 'curated'`, so a curated slug can never overwrite a machine-owned
// `source='espn'` home row. scripts/gen-uniform-seed.mts is the thin CLI around this.

const COLUMNS = [
  'id',
  'team_id',
  'kind',
  'name',
  'source',
  'year_start',
  'year_end',
  'is_current',
  'color_primary',
  'color_secondary',
  'color_accent',
  'ui_accent',
  'on_accent',
  'image_path',
] as const;

// Columns refreshed on conflict — everything except the id key and source (which stays
// 'curated'). updated_at is set to now() so a reseed reflects freshness.
const UPDATE_COLS = COLUMNS.filter((c) => c !== 'id' && c !== 'source');

function sqlStr(v: string): string {
  return `'${v.replace(/'/g, "''")}'`;
}

function sqlVal(v: string | number | boolean | null): string {
  if (v === null) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  return sqlStr(v);
}

function rowValues(u: (typeof UNIFORMS)[number]): string {
  const record: Record<string, string | number | boolean | null> = {
    id: `${u.teamId}-${u.slug}`,
    team_id: u.teamId,
    kind: u.kind,
    name: u.name,
    source: 'curated',
    year_start: u.yearStart,
    year_end: u.yearEnd,
    is_current: u.isCurrent,
    color_primary: u.colors.primary,
    color_secondary: u.colors.secondary,
    color_accent: u.colors.accent,
    ui_accent: u.colors.uiAccent,
    on_accent: u.colors.onAccent,
    image_path: u.imagePath ?? null,
  };
  return `  (${COLUMNS.map((c) => sqlVal(record[c])).join(', ')})`;
}

export function generateCuratedSeedSql(): string {
  const values = UNIFORMS.map(rowValues).join(',\n');
  const updates = UPDATE_COLS.map((c) => `${c} = excluded.${c}`).join(',\n  ');
  return `-- AUTO-GENERATED by scripts/gen-uniform-seed.mts from lib/uniforms/data.ts.
-- Do not edit by hand. Regenerate after changing the curated archive.
-- Idempotent, source-guarded: only rewrites source='curated' rows, never espn home rows.

insert into uniforms (${COLUMNS.join(', ')})
values
${values}
on conflict (id) do update set
  ${updates},
  updated_at = now()
where uniforms.source = 'curated';
`;
}
