// Provenance: user-supplied lions_leaping_lion.svg (DEP-475), club trademark/non-free art.
// Source SHA-256: 43e78fef4fc99e3a3a5d1d278ab5ed742794af621c85ef39081951fb80fe59be
// Direct source paths in original paint order; canvas and border paths are omitted.
// Placement reference: https://www.gridiron-uniforms.com/GUD/controller/controller.php?action=teams&team_id=DET
// Generated by scripts/uniform-draw/lions_decal.py; coordinates include placement.
export const LIONS_DECAL_PATHS = [
  { fill: 'silver', d: 'M342.838,340.041 L344.348,340.545 L346.614,341.804 L346.111,342.056 L343.593,341.049 L342.838,340.545 Z' },
] as const;
