import type { TeamRosterSeed } from '../types';
import { buildTeam, pl } from './_build';

// Minimal build-time seed for the ESPN ingestion: id/city/name/abbrev only. Everything
// that describes a team live — colors, conference/division, rosters — is sourced from
// ESPN at ingest time (scripts/ingest-espn.mts), NOT from here. This file just supplies
// the 32 team identities (our slug id ↔ ESPN abbrev) the ingestion loops over.
//
// The per-player entries below are stale point-in-time placeholders, NOT a live fallback.
// The app renders live rosters from the DB (dbRosterSource); there is no hand-authored
// roster fallback (see docs/espn.md). They persist only because the seed shape carries a
// players array and tests use them as fixtures — don't trust or maintain them as real
// roster data.

export const LEAGUE: TeamRosterSeed[] = [
  // ───────────── AFC East ─────────────
  buildTeam({
    id: 'bills',
    city: 'Buffalo',
    name: 'Bills',
    abbrev: 'BUF',
    colors: {
      primary: '#00338D',
      secondary: '#C60C30',
      accent: '#C60C30',
      uiAccent: '#5B9BFF',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Josh Allen', 17, 'QB', 1, { age: 28, exp: 7, college: 'Wyoming' }),
      pl('James Cook', 4, 'RB'),
      pl('Khalil Shakir', 10, 'WR'),
      pl('Keon Coleman', 0, 'WR'),
      pl('Curtis Samuel', 1, 'WR'),
      pl('Dalton Kincaid', 86, 'TE'),
      pl('Dion Dawkins', 73, 'LT'),
      pl('David Edwards', 76, 'LG'),
      pl('Connor McGovern', 66, 'C'),
      pl("O'Cyrus Torrence", 64, 'RG'),
      pl('Spencer Brown', 79, 'RT'),
      pl('Greg Rousseau', 50, 'DE'),
      pl('A.J. Epenesa', 57, 'DE'),
      pl('Ed Oliver', 91, 'DT'),
      pl('DaQuan Jones', 92, 'DT'),
      pl('Matt Milano', 58, 'LB'),
      pl('Terrel Bernard', 43, 'LB'),
      pl('Dorian Williams', 42, 'LB'),
      pl('Christian Benford', 47, 'CB'),
      pl('Rasul Douglas', 31, 'CB'),
      pl('Taylor Rapp', 20, 'S'),
      pl('Damar Hamlin', 3, 'S'),
      pl('Tyler Bass', 2, 'K'),
      pl('Sam Martin', 6, 'P'),
      pl('Reid Ferguson', 69, 'LS'),
    ],
    special: { k: 2, p: 6, ls: 69, kr: 1, pr: 10 },
  }),
  buildTeam({
    id: 'dolphins',
    city: 'Miami',
    name: 'Dolphins',
    abbrev: 'MIA',
    colors: {
      primary: '#008E97',
      secondary: '#FC4C02',
      accent: '#FC4C02',
      uiAccent: '#2DD4D4',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Tua Tagovailoa', 1, 'QB', 1, { age: 26, exp: 5, college: 'Alabama' }),
      pl("De'Von Achane", 28, 'RB'),
      pl('Tyreek Hill', 10, 'WR'),
      pl('Jaylen Waddle', 17, 'WR'),
      pl('Odell Beckham Jr.', 3, 'WR'),
      pl('Jonnu Smith', 9, 'TE'),
      pl('Terron Armstead', 72, 'LT'),
      pl('Robert Jones', 65, 'LG'),
      pl('Aaron Brewer', 55, 'C'),
      pl('Robert Hunt', 68, 'RG'),
      pl('Austin Jackson', 73, 'RT'),
      pl('Bradley Chubb', 2, 'DE'),
      pl('Jaelan Phillips', 15, 'DE'),
      pl('Zach Sieler', 92, 'DT'),
      pl('Calais Campbell', 93, 'DT'),
      pl('Jordyn Brooks', 20, 'LB'),
      pl('David Long Jr.', 51, 'LB'),
      pl('Tyrel Dodson', 53, 'LB'),
      pl('Jalen Ramsey', 5, 'CB'),
      pl('Kader Kohou', 4, 'CB'),
      pl('Jevon Holland', 8, 'S'),
      pl('Jordan Poyer', 21, 'S'),
      pl('Jason Sanders', 7, 'K'),
      pl('Jake Bailey', 16, 'P'),
      pl('Blake Ferguson', 47, 'LS'),
    ],
    special: { k: 7, p: 16, ls: 47, kr: 28, pr: 17 },
  }),
  buildTeam({
    id: 'patriots',
    city: 'New England',
    name: 'Patriots',
    abbrev: 'NE',
    colors: {
      primary: '#002244',
      secondary: '#C60C30',
      accent: '#B0B7BC',
      uiAccent: '#C8CDD6',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Drake Maye', 10, 'QB', 1, {
        age: 22,
        exp: 1,
        college: 'North Carolina',
        status: 'rookie',
      }),
      pl('Rhamondre Stevenson', 38, 'RB'),
      pl('DeMario Douglas', 81, 'WR'),
      pl('Kayshon Boutte', 9, 'WR'),
      pl("Ja'Lynn Polk", 1, 'WR'),
      pl('Hunter Henry', 85, 'TE'),
      pl('Vederian Lowe', 70, 'LT'),
      pl('Michael Jordan', 67, 'LG'),
      pl('David Andrews', 60, 'C'),
      pl('Mike Onwenu', 71, 'RG'),
      pl('Demontrey Jacobs', 64, 'RT'),
      pl('Keion White', 99, 'DE'),
      pl('Deatrich Wise Jr.', 91, 'DE'),
      pl('Christian Barmore', 90, 'DT'),
      pl('Davon Godchaux', 92, 'DT'),
      pl("Ja'Whaun Bentley", 8, 'LB'),
      pl('Jahlani Tavai', 48, 'LB'),
      pl('Anfernee Jennings', 58, 'LB'),
      pl('Christian Gonzalez', 0, 'CB'),
      pl('Marcus Jones', 25, 'CB'),
      pl('Kyle Dugger', 23, 'S'),
      pl('Jabrill Peppers', 5, 'S'),
      pl('Joey Slye', 6, 'K'),
      pl('Bryce Baringer', 17, 'P'),
      pl('Joe Cardona', 49, 'LS'),
    ],
    special: { k: 6, p: 17, ls: 49, kr: 25, pr: 81 },
  }),
  buildTeam({
    id: 'jets',
    city: 'New York',
    name: 'Jets',
    abbrev: 'NYJ',
    colors: {
      primary: '#125740',
      secondary: '#FFFFFF',
      accent: '#FFFFFF',
      uiAccent: '#4CC38A',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Aaron Rodgers', 8, 'QB', 1, { age: 41, exp: 20, college: 'California' }),
      pl('Breece Hall', 20, 'RB'),
      pl('Garrett Wilson', 17, 'WR'),
      pl('Davante Adams', 17, 'WR'),
      pl('Allen Lazard', 10, 'WR'),
      pl('Tyler Conklin', 83, 'TE'),
      pl('Tyron Smith', 78, 'LT'),
      pl('John Simpson', 76, 'LG'),
      pl('Joe Tippmann', 66, 'C'),
      pl('Alijah Vera-Tucker', 75, 'RG'),
      pl('Morgan Moses', 72, 'RT'),
      pl('Will McDonald IV', 99, 'DE'),
      pl('Jermaine Johnson', 11, 'DE'),
      pl('Quinnen Williams', 95, 'DT'),
      pl('Javon Kinlaw', 91, 'DT'),
      pl('C.J. Mosley', 57, 'LB'),
      pl('Quincy Williams', 56, 'LB'),
      pl('Jamien Sherwood', 44, 'LB'),
      pl('Sauce Gardner', 1, 'CB'),
      pl('D.J. Reed', 4, 'CB'),
      pl('Tony Adams', 22, 'S'),
      pl('Chuck Clark', 36, 'S'),
      pl('Greg Zuerlein', 9, 'K'),
      pl('Thomas Morstead', 18, 'P'),
      pl('Thomas Hennessy', 42, 'LS'),
    ],
    special: { k: 9, p: 18, ls: 42, kr: 20, pr: 10 },
  }),

  // ───────────── AFC North ─────────────
  buildTeam({
    id: 'ravens',
    city: 'Baltimore',
    name: 'Ravens',
    abbrev: 'BAL',
    colors: {
      primary: '#241773',
      secondary: '#000000',
      accent: '#9E7C0C',
      uiAccent: '#9F8CFF',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Lamar Jackson', 8, 'QB', 1, { age: 27, exp: 7, college: 'Louisville' }),
      pl('Derrick Henry', 22, 'RB', 1, { age: 30, exp: 9, college: 'Alabama' }),
      pl('Zay Flowers', 4, 'WR'),
      pl('Rashod Bateman', 7, 'WR'),
      pl('Nelson Agholor', 15, 'WR'),
      pl('Mark Andrews', 89, 'TE'),
      pl('Ronnie Stanley', 79, 'LT'),
      pl('Andrew Vorhees', 72, 'LG'),
      pl('Tyler Linderbaum', 64, 'C'),
      pl('Daniel Faalele', 77, 'RG'),
      pl('Patrick Mekari', 65, 'RT'),
      pl('Kyle Van Noy', 53, 'DE'),
      pl('Odafe Oweh', 99, 'DE'),
      pl('Nnamdi Madubuike', 92, 'DT'),
      pl('Michael Pierce', 97, 'DT'),
      pl('Roquan Smith', 0, 'LB'),
      pl('Trenton Simpson', 23, 'LB'),
      pl('Malik Harrison', 40, 'LB'),
      pl('Marlon Humphrey', 44, 'CB'),
      pl('Brandon Stephens', 21, 'CB'),
      pl('Kyle Hamilton', 14, 'S'),
      pl('Marcus Williams', 32, 'S'),
      pl('Justin Tucker', 9, 'K'),
      pl('Jordan Stout', 11, 'P'),
      pl('Nick Moore', 49, 'LS'),
    ],
    special: { k: 9, p: 11, ls: 49, kr: 4, pr: 4 },
  }),
  buildTeam({
    id: 'bengals',
    city: 'Cincinnati',
    name: 'Bengals',
    abbrev: 'CIN',
    colors: {
      primary: '#FB4F14',
      secondary: '#000000',
      accent: '#000000',
      uiAccent: '#FF6A33',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Joe Burrow', 9, 'QB', 1, { age: 27, exp: 5, college: 'LSU' }),
      pl('Chase Brown', 30, 'RB'),
      pl("Ja'Marr Chase", 1, 'WR', 1, { age: 24, exp: 4, college: 'LSU' }),
      pl('Tee Higgins', 5, 'WR'),
      pl('Andrei Iosivas', 80, 'WR'),
      pl('Mike Gesicki', 88, 'TE'),
      pl('Orlando Brown Jr.', 75, 'LT'),
      pl('Cordell Volson', 67, 'LG'),
      pl('Ted Karras', 64, 'C'),
      pl('Alex Cappa', 65, 'RG'),
      pl('Trent Brown', 77, 'RT'),
      pl('Trey Hendrickson', 91, 'DE'),
      pl('Sam Hubbard', 94, 'DE'),
      pl('B.J. Hill', 92, 'DT'),
      pl('Sheldon Rankins', 98, 'DT'),
      pl('Logan Wilson', 55, 'LB'),
      pl('Germaine Pratt', 57, 'LB'),
      pl('Akeem Davis-Gaither', 0, 'LB'),
      pl('Cam Taylor-Britt', 29, 'CB'),
      pl('D.J. Turner', 20, 'CB'),
      pl('Geno Stone', 22, 'S'),
      pl('Jordan Battle', 27, 'S'),
      pl('Evan McPherson', 2, 'K'),
      pl('Ryan Rehkow', 17, 'P'),
      pl('Cal Adomitis', 46, 'LS'),
    ],
    special: { k: 2, p: 17, ls: 46, kr: 30, pr: 1 },
  }),
  buildTeam({
    id: 'browns',
    city: 'Cleveland',
    name: 'Browns',
    abbrev: 'CLE',
    colors: {
      primary: '#311D00',
      secondary: '#FF3C00',
      accent: '#FF3C00',
      uiAccent: '#FF6A33',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Deshaun Watson', 4, 'QB', 1, { age: 29, exp: 8, college: 'Clemson' }),
      pl('Nick Chubb', 24, 'RB'),
      pl('Amari Cooper', 2, 'WR'),
      pl('Jerry Jeudy', 3, 'WR'),
      pl('Elijah Moore', 8, 'WR'),
      pl('David Njoku', 85, 'TE'),
      pl('Jedrick Wills Jr.', 71, 'LT'),
      pl('Joel Bitonio', 75, 'LG'),
      pl('Ethan Pocic', 55, 'C'),
      pl('Wyatt Teller', 77, 'RG'),
      pl('Jack Conklin', 78, 'RT'),
      pl('Myles Garrett', 95, 'DE', 1, { age: 28, exp: 8, college: 'Texas A&M' }),
      pl("Za'Darius Smith", 99, 'DE'),
      pl('Dalvin Tomlinson', 94, 'DT'),
      pl('Maliek Collins', 97, 'DT'),
      pl('Jordan Hicks', 58, 'LB'),
      pl('Jeremiah Owusu-Koramoah', 28, 'LB'),
      pl('Devin Bush', 30, 'LB'),
      pl('Denzel Ward', 21, 'CB'),
      pl('Greg Newsome II', 0, 'CB'),
      pl('Grant Delpit', 22, 'S'),
      pl('Juan Thornhill', 1, 'S'),
      pl('Dustin Hopkins', 7, 'K'),
      pl('Corey Bojorquez', 13, 'P'),
      pl('Charley Hughlett', 47, 'LS'),
    ],
    special: { k: 7, p: 13, ls: 47, kr: 8, pr: 8 },
  }),
  buildTeam({
    id: 'steelers',
    city: 'Pittsburgh',
    name: 'Steelers',
    abbrev: 'PIT',
    colors: {
      primary: '#FFB612',
      secondary: '#101820',
      accent: '#101820',
      uiAccent: '#FFB612',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Russell Wilson', 3, 'QB', 1, { age: 36, exp: 13, college: 'Wisconsin' }),
      pl('Najee Harris', 22, 'RB'),
      pl('George Pickens', 14, 'WR'),
      pl('Calvin Austin III', 19, 'WR'),
      pl('Van Jefferson', 84, 'WR'),
      pl('Pat Freiermuth', 88, 'TE'),
      pl('Dan Moore Jr.', 65, 'LT'),
      pl('Isaac Seumalo', 56, 'LG'),
      pl('Zach Frazier', 54, 'C'),
      pl('James Daniels', 78, 'RG'),
      pl('Broderick Jones', 74, 'RT'),
      pl('T.J. Watt', 90, 'DE', 1, { age: 30, exp: 8, college: 'Wisconsin' }),
      pl('Alex Highsmith', 56, 'DE'),
      pl('Cameron Heyward', 97, 'DT'),
      pl('Keeanu Benton', 95, 'DT'),
      pl('Patrick Queen', 6, 'LB'),
      pl('Elandon Roberts', 50, 'LB'),
      pl('Payton Wilson', 41, 'LB'),
      pl('Joey Porter Jr.', 24, 'CB'),
      pl('Donte Jackson', 26, 'CB'),
      pl('Minkah Fitzpatrick', 39, 'S'),
      pl('DeShon Elliott', 25, 'S'),
      pl('Chris Boswell', 9, 'K'),
      pl('Cameron Johnston', 11, 'P'),
      pl('Christian Kuntz', 46, 'LS'),
    ],
    special: { k: 9, p: 11, ls: 46, kr: 19, pr: 19 },
  }),

  // ───────────── AFC South ─────────────
  buildTeam({
    id: 'texans',
    city: 'Houston',
    name: 'Texans',
    abbrev: 'HOU',
    colors: {
      primary: '#03202F',
      secondary: '#A71930',
      accent: '#A71930',
      uiAccent: '#5B9BFF',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('C.J. Stroud', 7, 'QB', 1, { age: 23, exp: 2, college: 'Ohio State' }),
      pl('Joe Mixon', 28, 'RB'),
      pl('Nico Collins', 12, 'WR'),
      pl('Stefon Diggs', 1, 'WR'),
      pl('Tank Dell', 3, 'WR'),
      pl('Dalton Schultz', 86, 'TE'),
      pl('Laremy Tunsil', 78, 'LT'),
      pl('Kenyon Green', 59, 'LG'),
      pl('Juice Scruggs', 71, 'C'),
      pl('Shaq Mason', 69, 'RG'),
      pl('Tytus Howard', 71, 'RT'),
      pl('Will Anderson Jr.', 51, 'DE'),
      pl('Danielle Hunter', 55, 'DE'),
      pl('Folorunso Fatukasi', 98, 'DT'),
      pl('Sheldon Rankins', 99, 'DT'),
      pl('Azeez Al-Shaair', 0, 'LB'),
      pl("Henry To'oTo'o", 39, 'LB'),
      pl('Christian Harris', 48, 'LB'),
      pl('Derek Stingley Jr.', 24, 'CB'),
      pl('Kamari Lassiter', 4, 'CB'),
      pl('Jalen Pitre', 5, 'S'),
      pl('Jimmie Ward', 1, 'S'),
      pl("Ka'imi Fairbairn", 7, 'K'),
      pl('Tommy Townsend', 5, 'P'),
      pl('Jon Weeks', 46, 'LS'),
    ],
    special: { k: 7, p: 5, ls: 46, kr: 3, pr: 3 },
  }),
  buildTeam({
    id: 'colts',
    city: 'Indianapolis',
    name: 'Colts',
    abbrev: 'IND',
    colors: {
      primary: '#002C5F',
      secondary: '#A2AAAD',
      accent: '#A2AAAD',
      uiAccent: '#5B9BFF',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Anthony Richardson', 5, 'QB', 1, { age: 22, exp: 2, college: 'Florida' }),
      pl('Jonathan Taylor', 28, 'RB'),
      pl('Michael Pittman Jr.', 11, 'WR'),
      pl('Josh Downs', 1, 'WR'),
      pl('Alec Pierce', 14, 'WR'),
      pl('Kylen Granson', 83, 'TE'),
      pl('Bernhard Raimann', 79, 'LT'),
      pl('Quenton Nelson', 56, 'LG'),
      pl('Ryan Kelly', 78, 'C'),
      pl('Will Fries', 75, 'RG'),
      pl('Braden Smith', 72, 'RT'),
      pl('Kwity Paye', 51, 'DE'),
      pl('Dayo Odeyingbo', 54, 'DE'),
      pl('DeForest Buckner', 99, 'DT'),
      pl('Grover Stewart', 90, 'DT'),
      pl('Zaire Franklin', 44, 'LB'),
      pl('E.J. Speed', 45, 'LB'),
      pl('Segun Olubi', 41, 'LB'),
      pl('Kenny Moore II', 23, 'CB'),
      pl('JuJu Brents', 7, 'CB'),
      pl('Julian Blackmon', 32, 'S'),
      pl('Nick Cross', 20, 'S'),
      pl('Matt Gay', 8, 'K'),
      pl('Rigoberto Sanchez', 2, 'P'),
      pl('Luke Rhodes', 46, 'LS'),
    ],
    special: { k: 8, p: 2, ls: 46, kr: 1, pr: 1 },
  }),
  buildTeam({
    id: 'jaguars',
    city: 'Jacksonville',
    name: 'Jaguars',
    abbrev: 'JAX',
    colors: {
      primary: '#006778',
      secondary: '#D7A22A',
      accent: '#D7A22A',
      uiAccent: '#2DD4D4',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Trevor Lawrence', 16, 'QB', 1, { age: 25, exp: 4, college: 'Clemson' }),
      pl('Travis Etienne Jr.', 1, 'RB'),
      pl('Brian Thomas Jr.', 7, 'WR'),
      pl('Christian Kirk', 13, 'WR'),
      pl('Gabe Davis', 0, 'WR'),
      pl('Evan Engram', 17, 'TE'),
      pl('Cam Robinson', 74, 'LT'),
      pl('Ezra Cleveland', 72, 'LG'),
      pl('Mitch Morse', 61, 'C'),
      pl('Brandon Scherff', 68, 'RG'),
      pl('Anton Harrison', 71, 'RT'),
      pl('Josh Hines-Allen', 41, 'DE'),
      pl('Travon Walker', 44, 'DE'),
      pl('Arik Armstead', 91, 'DT'),
      pl('DaVon Hamilton', 52, 'DT'),
      pl('Foyesade Oluokun', 23, 'LB'),
      pl('Devin Lloyd', 0, 'LB'),
      pl('Chad Muma', 48, 'LB'),
      pl('Tyson Campbell', 32, 'CB'),
      pl('Ronald Darby', 21, 'CB'),
      pl('Andre Cisco', 5, 'S'),
      pl('Darnell Savage', 4, 'S'),
      pl('Cam Little', 39, 'K'),
      pl('Logan Cooke', 9, 'P'),
      pl('Ross Matiscik', 47, 'LS'),
    ],
    special: { k: 39, p: 9, ls: 47, kr: 1, pr: 13 },
  }),
  buildTeam({
    id: 'titans',
    city: 'Tennessee',
    name: 'Titans',
    abbrev: 'TEN',
    colors: {
      primary: '#0C2340',
      secondary: '#4B92DB',
      accent: '#4B92DB',
      uiAccent: '#5BA8E8',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Will Levis', 8, 'QB', 1, { age: 25, exp: 2, college: 'Kentucky' }),
      pl('Tony Pollard', 20, 'RB'),
      pl('Calvin Ridley', 0, 'WR'),
      pl('DeAndre Hopkins', 10, 'WR'),
      pl('Tyler Boyd', 18, 'WR'),
      pl('Chigoziem Okonkwo', 85, 'TE'),
      pl('JC Latham', 75, 'LT'),
      pl('Peter Skoronski', 77, 'LG'),
      pl('Lloyd Cushenberry III', 79, 'C'),
      pl('Dillon Radunz', 75, 'RG'),
      pl('Nicholas Petit-Frere', 78, 'RT'),
      pl('Harold Landry III', 58, 'DE'),
      pl('Arden Key', 49, 'DE'),
      pl('Jeffery Simmons', 98, 'DT'),
      pl("T'Vondre Sweat", 93, 'DT'),
      pl('Kenneth Murray Jr.', 56, 'LB'),
      pl('Jack Gibbens', 50, 'LB'),
      pl('James Williams', 6, 'LB'),
      pl("L'Jarius Sneed", 38, 'CB'),
      pl('Chidobe Awuzie', 24, 'CB'),
      pl('Amani Hooker', 37, 'S'),
      pl('Quandre Diggs', 6, 'S'),
      pl('Nick Folk', 2, 'K'),
      pl('Ryan Stonehouse', 4, 'P'),
      pl('Morgan Cox', 46, 'LS'),
    ],
    special: { k: 2, p: 4, ls: 46, kr: 18, pr: 18 },
  }),

  // ───────────── AFC West ─────────────
  buildTeam({
    id: 'broncos',
    city: 'Denver',
    name: 'Broncos',
    abbrev: 'DEN',
    colors: {
      primary: '#FB4F14',
      secondary: '#002244',
      accent: '#002244',
      uiAccent: '#FF6A33',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Bo Nix', 10, 'QB', 1, { age: 24, exp: 1, college: 'Oregon', status: 'rookie' }),
      pl('Javonte Williams', 33, 'RB'),
      pl('Courtland Sutton', 14, 'WR'),
      pl('Marvin Mims Jr.', 19, 'WR'),
      pl('Josh Reynolds', 8, 'WR'),
      pl('Adam Trautman', 82, 'TE'),
      pl('Garett Bolles', 72, 'LT'),
      pl('Ben Powers', 76, 'LG'),
      pl('Luke Wattenberg', 63, 'C'),
      pl('Quinn Meinerz', 77, 'RG'),
      pl('Mike McGlinchey', 69, 'RT'),
      pl('Nik Bonitto', 42, 'DE'),
      pl('Jonathon Cooper', 0, 'DE'),
      pl('Zach Allen', 99, 'DT'),
      pl('D.J. Jones', 93, 'DT'),
      pl('Alex Singleton', 49, 'LB'),
      pl('Cody Barton', 55, 'LB'),
      pl('Jonah Elliss', 97, 'LB'),
      pl('Patrick Surtain II', 2, 'CB'),
      pl('Riley Moss', 21, 'CB'),
      pl('Brandon Jones', 22, 'S'),
      pl('P.J. Locke', 6, 'S'),
      pl('Wil Lutz', 16, 'K'),
      pl('Riley Dixon', 9, 'P'),
      pl('Mitchell Fraboni', 47, 'LS'),
    ],
    special: { k: 16, p: 9, ls: 47, kr: 19, pr: 19 },
  }),
  buildTeam({
    id: 'chiefs',
    city: 'Kansas City',
    name: 'Chiefs',
    abbrev: 'KC',
    colors: {
      primary: '#E31837',
      secondary: '#FFB81C',
      accent: '#FFB81C',
      uiAccent: '#FF4D5E',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Patrick Mahomes', 15, 'QB', 1, { age: 29, exp: 8, college: 'Texas Tech' }),
      pl('Isiah Pacheco', 10, 'RB'),
      pl('Rashee Rice', 4, 'WR'),
      pl('Xavier Worthy', 1, 'WR'),
      pl('JuJu Smith-Schuster', 9, 'WR'),
      pl('Travis Kelce', 87, 'TE', 1, { age: 35, exp: 12, college: 'Cincinnati' }),
      pl('D.J. Humphries', 74, 'LT'),
      pl('Joe Thuney', 62, 'LG'),
      pl('Creed Humphrey', 52, 'C'),
      pl('Trey Smith', 65, 'RG'),
      pl('Jawaan Taylor', 75, 'RT'),
      pl('George Karlaftis', 56, 'DE'),
      pl('Charles Omenihu', 90, 'DE'),
      pl('Chris Jones', 95, 'DT', 1, { age: 30, exp: 9, college: 'Mississippi State' }),
      pl('Tershawn Wharton', 98, 'DT'),
      pl('Nick Bolton', 32, 'LB'),
      pl('Drue Tranquill', 23, 'LB'),
      pl('Leo Chenal', 54, 'LB'),
      pl('Trent McDuffie', 22, 'CB'),
      pl('Jaylen Watson', 35, 'CB'),
      pl('Justin Reid', 20, 'S'),
      pl('Bryan Cook', 6, 'S'),
      pl('Harrison Butker', 7, 'K'),
      pl('Matt Araiza', 19, 'P'),
      pl('James Winchester', 41, 'LS'),
    ],
    special: { k: 7, p: 19, ls: 41, kr: 1, pr: 4 },
  }),
  buildTeam({
    id: 'raiders',
    city: 'Las Vegas',
    name: 'Raiders',
    abbrev: 'LV',
    colors: {
      primary: '#000000',
      secondary: '#A5ACAF',
      accent: '#A5ACAF',
      uiAccent: '#C8CDD6',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Gardner Minshew', 15, 'QB', 1, { age: 28, exp: 6, college: 'Washington State' }),
      pl('Alexander Mattison', 22, 'RB'),
      pl('Davante Adams', 17, 'WR', 1, { age: 32, exp: 11, college: 'Fresno State' }),
      pl('Jakobi Meyers', 16, 'WR'),
      pl('Tre Tucker', 11, 'WR'),
      pl('Brock Bowers', 89, 'TE'),
      pl('Kolton Miller', 74, 'LT'),
      pl('Dylan Parham', 66, 'LG'),
      pl('Andre James', 68, 'C'),
      pl('Jackson Powers-Johnson', 72, 'RG'),
      pl('DJ Glaze', 67, 'RT'),
      pl('Maxx Crosby', 98, 'DE', 1, { age: 27, exp: 6, college: 'Eastern Michigan' }),
      pl('Malcolm Koonce', 51, 'DE'),
      pl('Christian Wilkins', 94, 'DT'),
      pl('John Jenkins', 95, 'DT'),
      pl('Robert Spillane', 41, 'LB'),
      pl('Divine Deablo', 5, 'LB'),
      pl('Luke Masterson', 59, 'LB'),
      pl('Jack Jones', 18, 'CB'),
      pl('Nate Hobbs', 39, 'CB'),
      pl("Tre'von Moehrig", 25, 'S'),
      pl('Marcus Epps', 1, 'S'),
      pl('Daniel Carlson', 2, 'K'),
      pl('AJ Cole', 6, 'P'),
      pl('Jacob Bobenmoyer', 47, 'LS'),
    ],
    special: { k: 2, p: 6, ls: 47, kr: 11, pr: 16 },
  }),
  buildTeam({
    id: 'chargers',
    city: 'Los Angeles',
    name: 'Chargers',
    abbrev: 'LAC',
    colors: {
      primary: '#0080C6',
      secondary: '#FFC20E',
      accent: '#FFC20E',
      uiAccent: '#36A7E0',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Justin Herbert', 10, 'QB', 1, { age: 26, exp: 5, college: 'Oregon' }),
      pl('J.K. Dobbins', 27, 'RB'),
      pl('Ladd McConkey', 15, 'WR'),
      pl('Quentin Johnston', 1, 'WR'),
      pl('Joshua Palmer', 5, 'WR'),
      pl('Will Dissly', 89, 'TE'),
      pl('Rashawn Slater', 70, 'LT'),
      pl('Zion Johnson', 77, 'LG'),
      pl('Bradley Bozeman', 75, 'C'),
      pl('Trey Pipkins III', 79, 'RG'),
      pl('Joe Alt', 76, 'RT'),
      pl('Joey Bosa', 97, 'DE'),
      pl('Khalil Mack', 52, 'DE', 1, { age: 33, exp: 11, college: 'Buffalo' }),
      pl('Poona Ford', 95, 'DT'),
      pl('Morgan Fox', 56, 'DT'),
      pl('Daiyan Henley', 0, 'LB'),
      pl('Denzel Perryman', 52, 'LB'),
      pl('Junior Colson', 33, 'LB'),
      pl('Asante Samuel Jr.', 26, 'CB'),
      pl('Kristian Fulton', 2, 'CB'),
      pl('Derwin James Jr.', 3, 'S'),
      pl('Alohi Gilman', 32, 'S'),
      pl('Cameron Dicker', 11, 'K'),
      pl('JK Scott', 16, 'P'),
      pl('Josh Harris', 47, 'LS'),
    ],
    special: { k: 11, p: 16, ls: 47, kr: 15, pr: 15 },
  }),

  // ───────────── NFC East ─────────────
  buildTeam({
    id: 'cowboys',
    city: 'Dallas',
    name: 'Cowboys',
    abbrev: 'DAL',
    colors: {
      primary: '#003594',
      secondary: '#869397',
      accent: '#869397',
      uiAccent: '#5B9BFF',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Dak Prescott', 4, 'QB', 1, { age: 31, exp: 9, college: 'Mississippi State' }),
      pl('Rico Dowdle', 23, 'RB'),
      pl('CeeDee Lamb', 88, 'WR', 1, { age: 25, exp: 5, college: 'Oklahoma' }),
      pl('Brandin Cooks', 3, 'WR'),
      pl('Jalen Tolbert', 1, 'WR'),
      pl('Jake Ferguson', 87, 'TE'),
      pl('Tyler Guyton', 60, 'LT'),
      pl('Tyler Smith', 73, 'LG'),
      pl('Cooper Beebe', 56, 'C'),
      pl('Zack Martin', 70, 'RG'),
      pl('Terence Steele', 78, 'RT'),
      pl('Micah Parsons', 11, 'DE', 1, { age: 25, exp: 4, college: 'Penn State' }),
      pl('DeMarcus Lawrence', 90, 'DE'),
      pl('Osa Odighizuwa', 97, 'DT'),
      pl('Mazi Smith', 58, 'DT'),
      pl('Eric Kendricks', 54, 'LB'),
      pl('DeMarvion Overshown', 0, 'LB'),
      pl('Marist Liufau', 35, 'LB'),
      pl('Trevon Diggs', 7, 'CB'),
      pl('DaRon Bland', 26, 'CB'),
      pl('Malik Hooker', 28, 'S'),
      pl('Donovan Wilson', 6, 'S'),
      pl('Brandon Aubrey', 17, 'K'),
      pl('Bryan Anger', 5, 'P'),
      pl('Trent Sieg', 47, 'LS'),
    ],
    special: { k: 17, p: 5, ls: 47, kr: 1, pr: 1 },
  }),
  buildTeam({
    id: 'giants',
    city: 'New York',
    name: 'Giants',
    abbrev: 'NYG',
    colors: {
      primary: '#0B2265',
      secondary: '#A71930',
      accent: '#A71930',
      uiAccent: '#5B9BFF',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Daniel Jones', 8, 'QB', 1, { age: 27, exp: 6, college: 'Duke' }),
      pl('Devin Singletary', 26, 'RB'),
      pl('Malik Nabers', 1, 'WR'),
      pl("Wan'Dale Robinson", 17, 'WR'),
      pl('Darius Slayton', 86, 'WR'),
      pl('Theo Johnson', 84, 'TE'),
      pl('Andrew Thomas', 78, 'LT'),
      pl('Jon Runyan Jr.', 76, 'LG'),
      pl('John Michael Schmitz', 61, 'C'),
      pl('Greg Van Roten', 67, 'RG'),
      pl('Jermaine Eluemunor', 72, 'RT'),
      pl('Brian Burns', 0, 'DE'),
      pl('Kayvon Thibodeaux', 5, 'DE'),
      pl('Dexter Lawrence II', 97, 'DT'),
      pl('Rakeem Nunez-Roches', 56, 'DT'),
      pl('Bobby Okereke', 58, 'LB'),
      pl('Micah McFadden', 41, 'LB'),
      pl('Darius Muasau', 44, 'LB'),
      pl('Deonte Banks', 25, 'CB'),
      pl("Cor'Dale Flott", 28, 'CB'),
      pl('Jason Pinnock', 27, 'S'),
      pl('Tyler Nubin', 31, 'S'),
      pl('Graham Gano', 5, 'K'),
      pl('Jamie Gillan', 6, 'P'),
      pl('Casey Kreiter', 58, 'LS'),
    ],
    special: { k: 5, p: 6, ls: 58, kr: 17, pr: 17 },
  }),
  buildTeam({
    id: 'eagles',
    city: 'Philadelphia',
    name: 'Eagles',
    abbrev: 'PHI',
    colors: {
      primary: '#004C54',
      secondary: '#A5ACAF',
      accent: '#A5ACAF',
      uiAccent: '#2FA3A3',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Jalen Hurts', 1, 'QB', 1, { age: 26, exp: 5, college: 'Oklahoma' }),
      pl('Saquon Barkley', 26, 'RB', 1, { age: 27, exp: 7, college: 'Penn State' }),
      pl('A.J. Brown', 11, 'WR', 1, { age: 27, exp: 6, college: 'Ole Miss' }),
      pl('DeVonta Smith', 6, 'WR'),
      pl('Jahan Dotson', 2, 'WR'),
      pl('Dallas Goedert', 88, 'TE'),
      pl('Jordan Mailata', 68, 'LT'),
      pl('Landon Dickerson', 69, 'LG'),
      pl('Cam Jurgens', 51, 'C'),
      pl('Mekhi Becton', 77, 'RG'),
      pl('Lane Johnson', 65, 'RT'),
      pl('Josh Sweat', 94, 'DE'),
      pl('Bryce Huff', 17, 'DE'),
      pl('Jalen Carter', 98, 'DT'),
      pl('Jordan Davis', 90, 'DT'),
      pl('Zack Baun', 53, 'LB'),
      pl('Nakobe Dean', 17, 'LB'),
      pl('Devin White', 40, 'LB'),
      pl('Darius Slay', 2, 'CB'),
      pl('Quinyon Mitchell', 27, 'CB'),
      pl('Reed Blankenship', 32, 'S'),
      pl('C.J. Gardner-Johnson', 8, 'S'),
      pl('Jake Elliott', 4, 'K'),
      pl('Braden Mann', 7, 'P'),
      pl('Charley Hughlett', 46, 'LS'),
    ],
    special: { k: 4, p: 7, ls: 46, kr: 6, pr: 6 },
  }),
  buildTeam({
    id: 'commanders',
    city: 'Washington',
    name: 'Commanders',
    abbrev: 'WAS',
    colors: {
      primary: '#5A1414',
      secondary: '#FFB612',
      accent: '#FFB612',
      uiAccent: '#FFB612',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Jayden Daniels', 5, 'QB', 1, { age: 24, exp: 1, college: 'LSU', status: 'rookie' }),
      pl('Brian Robinson Jr.', 8, 'RB'),
      pl('Terry McLaurin', 17, 'WR'),
      pl('Noah Brown', 85, 'WR'),
      pl('Dyami Brown', 2, 'WR'),
      pl('Zach Ertz', 86, 'TE'),
      pl('Brandon Coleman', 79, 'LT'),
      pl('Nick Allegretti', 73, 'LG'),
      pl('Tyler Biadasz', 63, 'C'),
      pl('Sam Cosmi', 76, 'RG'),
      pl('Andrew Wylie', 77, 'RT'),
      pl('Dorance Armstrong', 92, 'DE'),
      pl('Clelin Ferrell', 99, 'DE'),
      pl('Daron Payne', 94, 'DT'),
      pl('Jonathan Allen', 93, 'DT'),
      pl('Bobby Wagner', 54, 'LB', 1, { age: 34, exp: 13, college: 'Utah State' }),
      pl('Frankie Luvu', 4, 'LB'),
      pl('Jamin Davis', 52, 'LB'),
      pl('Marshon Lattimore', 2, 'CB'),
      pl('Benjamin St-Juste', 25, 'CB'),
      pl('Quan Martin', 20, 'S'),
      pl('Jeremy Chinn', 0, 'S'),
      pl('Austin Seibert', 3, 'K'),
      pl('Tress Way', 5, 'P'),
      pl('Tyler Ott', 47, 'LS'),
    ],
    special: { k: 3, p: 5, ls: 47, kr: 2, pr: 2 },
  }),

  // ───────────── NFC North ─────────────
  buildTeam({
    id: 'bears',
    city: 'Chicago',
    name: 'Bears',
    abbrev: 'CHI',
    colors: {
      primary: '#0B162A',
      secondary: '#C83803',
      accent: '#C83803',
      uiAccent: '#FF6A33',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Caleb Williams', 18, 'QB', 1, { age: 23, exp: 1, college: 'USC', status: 'rookie' }),
      pl("D'Andre Swift", 4, 'RB'),
      pl('DJ Moore', 2, 'WR'),
      pl('Keenan Allen', 13, 'WR'),
      pl('Rome Odunze', 15, 'WR'),
      pl('Cole Kmet', 85, 'TE'),
      pl('Braxton Jones', 70, 'LT'),
      pl('Teven Jenkins', 76, 'LG'),
      pl('Coleman Shelton', 65, 'C'),
      pl('Nate Davis', 64, 'RG'),
      pl('Darnell Wright', 58, 'RT'),
      pl('Montez Sweat', 98, 'DE'),
      pl('DeMarcus Walker', 95, 'DE'),
      pl('Gervon Dexter Sr.', 99, 'DT'),
      pl('Andrew Billings', 97, 'DT'),
      pl('T.J. Edwards', 53, 'LB'),
      pl('Tremaine Edmunds', 49, 'LB'),
      pl('Jack Sanborn', 57, 'LB'),
      pl('Jaylon Johnson', 33, 'CB'),
      pl('Tyrique Stevenson', 29, 'CB'),
      pl('Kevin Byard III', 31, 'S'),
      pl('Jaquan Brisker', 9, 'S'),
      pl('Cairo Santos', 8, 'K'),
      pl('Tory Taylor', 9, 'P'),
      pl('Patrick Scales', 48, 'LS'),
    ],
    special: { k: 8, p: 9, ls: 48, kr: 15, pr: 2 },
  }),
  buildTeam({
    id: 'lions',
    city: 'Detroit',
    name: 'Lions',
    abbrev: 'DET',
    colors: {
      primary: '#0076B6',
      secondary: '#B0B7BC',
      accent: '#B0B7BC',
      uiAccent: '#36A7E0',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Jared Goff', 16, 'QB', 1, { age: 30, exp: 9, college: 'California' }),
      pl('Jahmyr Gibbs', 26, 'RB'),
      pl('Amon-Ra St. Brown', 14, 'WR', 1, { age: 25, exp: 4, college: 'USC' }),
      pl('Jameson Williams', 9, 'WR'),
      pl('Tim Patrick', 12, 'WR'),
      pl('Sam LaPorta', 87, 'TE'),
      pl('Taylor Decker', 68, 'LT'),
      pl('Graham Glasgow', 60, 'LG'),
      pl('Frank Ragnow', 77, 'C'),
      pl('Kevin Zeitler', 70, 'RG'),
      pl('Penei Sewell', 58, 'RT'),
      pl('Aidan Hutchinson', 97, 'DE', 1, { age: 24, exp: 3, college: 'Michigan' }),
      pl('Marcus Davenport', 94, 'DE'),
      pl('Alim McNeill', 54, 'DT'),
      pl('D.J. Reader', 98, 'DT'),
      pl('Alex Anzalone', 34, 'LB'),
      pl('Jack Campbell', 46, 'LB'),
      pl('Derrick Barnes', 55, 'LB'),
      pl('Carlton Davis III', 1, 'CB'),
      pl('Terrion Arnold', 0, 'CB'),
      pl('Brian Branch', 32, 'S'),
      pl('Kerby Joseph', 31, 'S'),
      pl('Jake Bates', 39, 'K'),
      pl('Jack Fox', 3, 'P'),
      pl('Scott Daly', 43, 'LS'),
    ],
    special: { k: 39, p: 3, ls: 43, kr: 9, pr: 14 },
  }),
  buildTeam({
    id: 'packers',
    city: 'Green Bay',
    name: 'Packers',
    abbrev: 'GB',
    colors: {
      primary: '#203731',
      secondary: '#FFB612',
      accent: '#FFB612',
      uiAccent: '#FFB612',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Jordan Love', 10, 'QB', 1, { age: 26, exp: 5, college: 'Utah State' }),
      pl('Josh Jacobs', 8, 'RB'),
      pl('Jayden Reed', 11, 'WR'),
      pl('Romeo Doubs', 87, 'WR'),
      pl('Dontayvion Wicks', 13, 'WR'),
      pl('Tucker Kraft', 85, 'TE'),
      pl('Rasheed Walker', 63, 'LT'),
      pl('Elgton Jenkins', 74, 'LG'),
      pl('Josh Myers', 71, 'C'),
      pl('Sean Rhyan', 75, 'RG'),
      pl('Zach Tom', 50, 'RT'),
      pl('Rashan Gary', 52, 'DE'),
      pl('Preston Smith', 91, 'DE'),
      pl('Kenny Clark', 97, 'DT'),
      pl('Devonte Wyatt', 95, 'DT'),
      pl('Quay Walker', 7, 'LB'),
      pl('Isaiah McDuffie', 58, 'LB'),
      pl('Edgerrin Cooper', 56, 'LB'),
      pl('Jaire Alexander', 23, 'CB'),
      pl('Keisean Nixon', 25, 'CB'),
      pl('Xavier McKinney', 29, 'S'),
      pl('Javon Bullard', 20, 'S'),
      pl('Brayden Narveson', 36, 'K'),
      pl('Daniel Whelan', 19, 'P'),
      pl('Matt Orzech', 48, 'LS'),
    ],
    special: { k: 36, p: 19, ls: 48, kr: 25, pr: 11 },
  }),
  buildTeam({
    id: 'vikings',
    city: 'Minnesota',
    name: 'Vikings',
    abbrev: 'MIN',
    colors: {
      primary: '#4F2683',
      secondary: '#FFC62F',
      accent: '#FFC62F',
      uiAccent: '#FFC62F',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Sam Darnold', 14, 'QB', 1, { age: 27, exp: 7, college: 'USC' }),
      pl('Aaron Jones', 33, 'RB'),
      pl('Justin Jefferson', 18, 'WR', 1, { age: 25, exp: 5, college: 'LSU' }),
      pl('Jordan Addison', 3, 'WR'),
      pl('Jalen Nailor', 83, 'WR'),
      pl('T.J. Hockenson', 87, 'TE'),
      pl('Cam Robinson', 74, 'LT'),
      pl('Blake Brandel', 64, 'LG'),
      pl('Garrett Bradbury', 56, 'C'),
      pl('Ed Ingram', 67, 'RG'),
      pl("Brian O'Neill", 75, 'RT'),
      pl('Jonathan Greenard', 58, 'DE'),
      pl('Andrew Van Ginkel', 43, 'DE'),
      pl('Harrison Phillips', 97, 'DT'),
      pl('Jerry Tillery', 95, 'DT'),
      pl('Ivan Pace Jr.', 0, 'LB'),
      pl('Blake Cashman', 51, 'LB'),
      pl('Kamu Grugier-Hill', 54, 'LB'),
      pl('Stephon Gilmore', 21, 'CB'),
      pl('Byron Murphy Jr.', 7, 'CB'),
      pl('Harrison Smith', 22, 'S'),
      pl('Camryn Bynum', 24, 'S'),
      pl('Will Reichard', 16, 'K'),
      pl('Ryan Wright', 19, 'P'),
      pl('Andrew DePaola', 42, 'LS'),
    ],
    special: { k: 16, p: 19, ls: 42, kr: 83, pr: 3 },
  }),

  // ───────────── NFC South ─────────────
  buildTeam({
    id: 'falcons',
    city: 'Atlanta',
    name: 'Falcons',
    abbrev: 'ATL',
    colors: {
      primary: '#A71930',
      secondary: '#000000',
      accent: '#000000',
      uiAccent: '#FF4D5E',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Kirk Cousins', 18, 'QB', 1, { age: 36, exp: 13, college: 'Michigan State' }),
      pl('Bijan Robinson', 7, 'RB'),
      pl('Drake London', 5, 'WR'),
      pl('Darnell Mooney', 1, 'WR'),
      pl('Ray-Ray McCloud III', 14, 'WR'),
      pl('Kyle Pitts', 8, 'TE'),
      pl('Jake Matthews', 70, 'LT'),
      pl('Matthew Bergeron', 65, 'LG'),
      pl('Drew Dalman', 67, 'C'),
      pl('Chris Lindstrom', 63, 'RG'),
      pl('Kaleb McGary', 76, 'RT'),
      pl('Lorenzo Carter', 9, 'DE'),
      pl('Arnold Ebiketie', 17, 'DE'),
      pl('Grady Jarrett', 97, 'DT'),
      pl('David Onyemata', 90, 'DT'),
      pl('Kaden Elliss', 55, 'LB'),
      pl('Nate Landman', 44, 'LB'),
      pl('Troy Andersen', 44, 'LB'),
      pl('A.J. Terrell', 24, 'CB'),
      pl('Mike Hughes', 21, 'CB'),
      pl('Jessie Bates III', 3, 'S'),
      pl('Justin Simmons', 31, 'S'),
      pl('Younghoe Koo', 7, 'K'),
      pl('Bradley Pinion', 13, 'P'),
      pl('Liam McCullough', 48, 'LS'),
    ],
    special: { k: 7, p: 13, ls: 48, kr: 14, pr: 14 },
  }),
  buildTeam({
    id: 'panthers',
    city: 'Carolina',
    name: 'Panthers',
    abbrev: 'CAR',
    colors: {
      primary: '#0085CA',
      secondary: '#101820',
      accent: '#101820',
      uiAccent: '#36A7E0',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Bryce Young', 9, 'QB', 1, { age: 23, exp: 2, college: 'Alabama' }),
      pl('Chuba Hubbard', 30, 'RB'),
      pl('Diontae Johnson', 5, 'WR'),
      pl('Adam Thielen', 19, 'WR'),
      pl('Xavier Legette', 17, 'WR'),
      pl('Tommy Tremble', 82, 'TE'),
      pl('Ikem Ekwonu', 79, 'LT'),
      pl('Damien Lewis', 68, 'LG'),
      pl('Austin Corbett', 63, 'C'),
      pl('Robert Hunt', 50, 'RG'),
      pl('Taylor Moton', 72, 'RT'),
      pl('Jadeveon Clowney', 7, 'DE'),
      pl('DJ Wonnum', 98, 'DE'),
      pl('Derrick Brown', 95, 'DT'),
      pl('Shy Tuttle', 99, 'DT'),
      pl('Josey Jewell', 47, 'LB'),
      pl('Shaq Thompson', 54, 'LB'),
      pl('Trevin Wallace', 30, 'LB'),
      pl('Jaycee Horn', 8, 'CB'),
      pl('Dane Jackson', 0, 'CB'),
      pl('Xavier Woods', 25, 'S'),
      pl('Nick Scott', 33, 'S'),
      pl('Eddy Pineiro', 4, 'K'),
      pl('Johnny Hekker', 6, 'P'),
      pl('JJ Jansen', 44, 'LS'),
    ],
    special: { k: 4, p: 6, ls: 44, kr: 17, pr: 5 },
  }),
  buildTeam({
    id: 'saints',
    city: 'New Orleans',
    name: 'Saints',
    abbrev: 'NO',
    colors: {
      primary: '#D3BC8D',
      secondary: '#101820',
      accent: '#101820',
      uiAccent: '#E2CC9A',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Derek Carr', 4, 'QB', 1, { age: 33, exp: 11, college: 'Fresno State' }),
      pl('Alvin Kamara', 41, 'RB'),
      pl('Chris Olave', 12, 'WR'),
      pl('Rashid Shaheed', 22, 'WR'),
      pl('Cedrick Wilson Jr.', 11, 'WR'),
      pl('Juwan Johnson', 83, 'TE'),
      pl('Taliese Fuaga', 75, 'LT'),
      pl('Lucas Patrick', 62, 'LG'),
      pl('Erik McCoy', 78, 'C'),
      pl('Cesar Ruiz', 51, 'RG'),
      pl('Trevor Penning', 70, 'RT'),
      pl('Cameron Jordan', 94, 'DE'),
      pl('Carl Granderson', 96, 'DE'),
      pl('Bryan Bresee', 90, 'DT'),
      pl('Nathan Shepherd', 93, 'DT'),
      pl('Demario Davis', 56, 'LB'),
      pl('Pete Werner', 20, 'LB'),
      pl('Willie Gay Jr.', 6, 'LB'),
      pl('Marshon Lattimore', 23, 'CB'),
      pl('Paulson Adebo', 29, 'CB'),
      pl('Tyrann Mathieu', 32, 'S'),
      pl('Will Harris', 28, 'S'),
      pl('Blake Grupe', 19, 'K'),
      pl('Matthew Hayball', 7, 'P'),
      pl('Zach Wood', 49, 'LS'),
    ],
    special: { k: 19, p: 7, ls: 49, kr: 22, pr: 22 },
  }),
  buildTeam({
    id: 'buccaneers',
    city: 'Tampa Bay',
    name: 'Buccaneers',
    abbrev: 'TB',
    colors: {
      primary: '#D50A0A',
      secondary: '#34302B',
      accent: '#FF7900',
      uiAccent: '#FF4D4D',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Baker Mayfield', 6, 'QB', 1, { age: 29, exp: 7, college: 'Oklahoma' }),
      pl('Rachaad White', 1, 'RB'),
      pl('Mike Evans', 13, 'WR', 1, { age: 31, exp: 11, college: 'Texas A&M' }),
      pl('Chris Godwin', 14, 'WR'),
      pl('Jalen McMillan', 18, 'WR'),
      pl('Cade Otton', 88, 'TE'),
      pl('Tristan Wirfs', 78, 'LT'),
      pl('Ben Bredeson', 68, 'LG'),
      pl('Graham Barton', 56, 'C'),
      pl('Cody Mauch', 69, 'RG'),
      pl('Luke Goedeke', 67, 'RT'),
      pl('YaYa Diaby', 0, 'DE'),
      pl('Logan Hall', 90, 'DE'),
      pl('Vita Vea', 50, 'DT'),
      pl('Calijah Kancey', 94, 'DT'),
      pl('Lavonte David', 54, 'LB'),
      pl('K.J. Britt', 52, 'LB'),
      pl('SirVocea Dennis', 11, 'LB'),
      pl('Jamel Dean', 35, 'CB'),
      pl('Zyon McCollum', 27, 'CB'),
      pl('Antoine Winfield Jr.', 31, 'S'),
      pl('Jordan Whitehead', 33, 'S'),
      pl('Chase McLaughlin', 4, 'K'),
      pl('Jake Camarda', 5, 'P'),
      pl('Evan Deckers', 48, 'LS'),
    ],
    special: { k: 4, p: 5, ls: 48, kr: 18, pr: 14 },
  }),

  // ───────────── NFC West ─────────────
  buildTeam({
    id: 'seahawks',
    city: 'Seattle',
    name: 'Seahawks',
    abbrev: 'SEA',
    colors: {
      primary: '#002244',
      secondary: '#69BE28',
      accent: '#A5ACAF',
      uiAccent: '#69BE28',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Geno Smith', 7, 'QB', 1, { age: 34, exp: 12, college: 'West Virginia' }),
      pl('Kenneth Walker III', 9, 'RB', 1, { age: 24, exp: 3, college: 'Michigan State' }),
      pl('Jaxon Smith-Njigba', 11, 'WR'),
      pl('DK Metcalf', 14, 'WR'),
      pl('Tyler Lockett', 16, 'WR'),
      pl('Noah Fant', 87, 'TE'),
      pl('Charles Cross', 67, 'LT'),
      pl('Laken Tomlinson', 77, 'LG'),
      pl('Connor Williams', 52, 'C'),
      pl('Anthony Bradford', 66, 'RG'),
      pl('Abe Lucas', 72, 'RT'),
      pl('Uchenna Nwosu', 10, 'DE'),
      pl('Boye Mafe', 53, 'DE'),
      pl('Leonard Williams', 99, 'DT'),
      pl('Jarran Reed', 90, 'DT'),
      pl('Jerome Baker', 17, 'LB'),
      pl('Tyrel Dodson', 51, 'LB'),
      pl('Dre Greenlaw', 57, 'LB'),
      pl('Devon Witherspoon', 21, 'CB'),
      pl('Riq Woolen', 27, 'CB'),
      pl('Quandre Diggs', 6, 'S'),
      pl('Julian Love', 37, 'S'),
      pl('Jason Myers', 3, 'K'),
      pl('Michael Dickson', 4, 'P'),
      pl('Chris Stoll', 49, 'LS'),
    ],
    special: { k: 3, p: 4, ls: 49, kr: 16, pr: 11 },
  }),
  buildTeam({
    id: 'cardinals',
    city: 'Arizona',
    name: 'Cardinals',
    abbrev: 'ARI',
    colors: {
      primary: '#97233F',
      secondary: '#000000',
      accent: '#FFB612',
      uiAccent: '#FF4D6A',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Kyler Murray', 1, 'QB', 1, { age: 27, exp: 6, college: 'Oklahoma' }),
      pl('James Conner', 6, 'RB'),
      pl('Marvin Harrison Jr.', 18, 'WR'),
      pl('Michael Wilson', 14, 'WR'),
      pl('Greg Dortch', 83, 'WR'),
      pl('Trey McBride', 85, 'TE'),
      pl('Paris Johnson Jr.', 77, 'LT'),
      pl('Evan Brown', 63, 'LG'),
      pl('Hjalte Froholdt', 51, 'C'),
      pl('Will Hernandez', 76, 'RG'),
      pl('Jonah Williams', 73, 'RT'),
      pl('Zaven Collins', 25, 'DE'),
      pl('Dennis Gardeck', 45, 'DE'),
      pl('Justin Jones', 93, 'DT'),
      pl('Bilal Nichols', 91, 'DT'),
      pl('Kyzir White', 7, 'LB'),
      pl('Mack Wilson Sr.', 51, 'LB'),
      pl('Owen Pappoe', 50, 'LB'),
      pl('Sean Murphy-Bunting', 0, 'CB'),
      pl('Garrett Williams', 22, 'CB'),
      pl('Budda Baker', 3, 'S'),
      pl('Jalen Thompson', 34, 'S'),
      pl('Matt Prater', 5, 'K'),
      pl('Blake Gillikin', 4, 'P'),
      pl('Aaron Brewer', 46, 'LS'),
    ],
    special: { k: 5, p: 4, ls: 46, kr: 83, pr: 83 },
  }),
  buildTeam({
    id: 'rams',
    city: 'Los Angeles',
    name: 'Rams',
    abbrev: 'LAR',
    colors: {
      primary: '#003594',
      secondary: '#FFA300',
      accent: '#FFA300',
      uiAccent: '#FFC20E',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Matthew Stafford', 9, 'QB', 1, { age: 36, exp: 16, college: 'Georgia' }),
      pl('Kyren Williams', 23, 'RB'),
      pl('Cooper Kupp', 10, 'WR'),
      pl('Puka Nacua', 17, 'WR'),
      pl('Demarcus Robinson', 15, 'WR'),
      pl('Colby Parkinson', 84, 'TE'),
      pl('Alaric Jackson', 77, 'LT'),
      pl('Steve Avila', 73, 'LG'),
      pl('Beaux Limmer', 52, 'C'),
      pl('Kevin Dotson', 50, 'RG'),
      pl('Rob Havenstein', 79, 'RT'),
      pl('Jared Verse', 8, 'DE'),
      pl('Byron Young', 0, 'DE'),
      pl('Kobie Turner', 91, 'DT'),
      pl('Braden Fiske', 55, 'DT'),
      pl('Christian Rozeboom', 56, 'LB'),
      pl('Troy Reeder', 51, 'LB'),
      pl('Omar Speights', 48, 'LB'),
      pl('Darious Williams', 31, 'CB'),
      pl('Cobie Durant', 14, 'CB'),
      pl('Kamren Curl', 22, 'S'),
      pl('Kamren Kinchens', 27, 'S'),
      pl('Joshua Karty', 16, 'K'),
      pl('Ethan Evans', 12, 'P'),
      pl('Alex Ward', 47, 'LS'),
    ],
    special: { k: 16, p: 12, ls: 47, kr: 15, pr: 15 },
  }),
  buildTeam({
    id: '49ers',
    city: 'San Francisco',
    name: '49ers',
    abbrev: 'SF',
    colors: {
      primary: '#AA0000',
      secondary: '#B3995D',
      accent: '#B3995D',
      uiAccent: '#FF4D4D',
      onAccent: '#0a0e1a',
    },
    players: [
      pl('Brock Purdy', 13, 'QB', 1, { age: 25, exp: 3, college: 'Iowa State' }),
      pl('Christian McCaffrey', 23, 'RB', 1, { age: 28, exp: 8, college: 'Stanford' }),
      pl('Deebo Samuel', 19, 'WR'),
      pl('Brandon Aiyuk', 11, 'WR'),
      pl('Jauan Jennings', 15, 'WR'),
      pl('George Kittle', 85, 'TE', 1, { age: 31, exp: 8, college: 'Iowa' }),
      pl('Trent Williams', 71, 'LT', 1, { age: 36, exp: 15, college: 'Oklahoma' }),
      pl('Aaron Banks', 65, 'LG'),
      pl('Jake Brendel', 64, 'C'),
      pl('Dominick Puni', 77, 'RG'),
      pl('Colton McKivitz', 68, 'RT'),
      pl('Nick Bosa', 97, 'DE', 1, { age: 27, exp: 6, college: 'Ohio State' }),
      pl('Leonard Floyd', 56, 'DE'),
      pl('Javon Hargrave', 98, 'DT'),
      pl('Maliek Collins', 96, 'DT'),
      pl('Fred Warner', 54, 'LB', 1, { age: 28, exp: 7, college: 'BYU' }),
      pl('Dre Greenlaw', 57, 'LB'),
      pl("De'Vondre Campbell", 59, 'LB'),
      pl('Charvarius Ward', 7, 'CB'),
      pl('Deommodore Lenoir', 2, 'CB'),
      pl('Talanoa Hufanga', 29, 'S'),
      pl("Ji'Ayir Brown", 27, 'S'),
      pl('Jake Moody', 4, 'K'),
      pl('Mitch Wishnowsky', 18, 'P'),
      pl('Taybor Pepper', 46, 'LS'),
    ],
    special: { k: 4, p: 18, ls: 46, kr: 19, pr: 19 },
  }),
];
