import type { Player, FieldSlot, TeamRoster } from "../types";

const PLAYERS: Player[] = [
  // ───────── OFFENSE ─────────
  // QB
  {
    id: "geno-smith",
    name: "Geno Smith",
    number: 7,
    position: "QB",
    depthRank: 1,
    status: "starter",
    age: 34,
    college: "West Virginia",
    experience: 12,
    height: "6'3\"",
    weight: 221,
    bio: "The comeback story of the league. After years as a backup, Geno led Seattle to back-to-back playoff appearances and won NFL Comeback Player of the Year in 2022.",
    stats: { Rating: "97.3", Yards: "3891", TDs: 20, INTs: 9 },
  },
  {
    id: "sam-howell",
    name: "Sam Howell",
    number: 19,
    position: "QB",
    depthRank: 2,
    status: "backup",
    age: 24,
    college: "North Carolina",
    experience: 3,
    height: "6'1\"",
    weight: 218,
    bio: "Veteran insurance with starting experience from his time in Washington. Provides a capable bridge if Geno misses time.",
  },
  {
    id: "pj-walker",
    name: "P.J. Walker",
    number: 15,
    position: "QB",
    depthRank: 3,
    status: "backup",
    age: 30,
    college: "Temple",
    experience: 5,
    height: "5'11\"",
    weight: 215,
    bio: "Journeyman QB3 who keeps Seattle's quarterback room stable through the season.",
  },

  // RB
  {
    id: "kenneth-walker",
    name: "Kenneth Walker III",
    number: 9,
    position: "RB",
    depthRank: 1,
    status: "starter",
    age: 24,
    college: "Michigan State",
    experience: 3,
    height: "5'9\"",
    weight: 211,
    bio: "KWIII is an explosive, elusive back who burst onto the scene with 1,050 rushing yards as a rookie. A key piece of Seattle's ground game identity.",
    stats: { Yards: 1040, YPC: 4.4, TDs: 9 },
  },
  {
    id: "zach-charbonnet",
    name: "Zach Charbonnet",
    number: 26,
    position: "RB",
    depthRank: 2,
    status: "backup",
    age: 24,
    college: "UCLA",
    experience: 2,
    height: "6'0\"",
    weight: 220,
    bio: "A complementary back with three-down ability. His patient running style and pass-blocking chops make him a reliable 1B option behind KWIII.",
  },
  {
    id: "kenny-mcintosh",
    name: "Kenny McIntosh",
    number: 28,
    position: "RB",
    depthRank: 3,
    status: "backup",
    age: 25,
    college: "Georgia",
    experience: 2,
    height: "6'1\"",
    weight: 212,
    bio: "Pass-catching specialist who can flex out wide. Earns snaps in third-down packages.",
  },

  // WR
  {
    id: "jaxon-smith-njigba",
    name: "Jaxon Smith-Njigba",
    number: 11,
    position: "WR",
    depthRank: 1,
    status: "starter",
    age: 23,
    college: "Ohio State",
    experience: 2,
    height: "6'0\"",
    weight: 196,
    bio: "The 2023 first-round pick is developing into a true No. 1 receiver. His route-running precision and YAC ability make him a matchup nightmare in the slot.",
    stats: { Rec: 81, Yards: 1024, TDs: 4 },
  },
  {
    id: "dk-metcalf",
    name: "DK Metcalf",
    number: 14,
    position: "WR",
    depthRank: 1,
    status: "starter",
    age: 27,
    college: "Mississippi",
    experience: 6,
    height: "6'4\"",
    weight: 235,
    bio: "One of the most physically imposing receivers in the NFL. DK's combination of size and speed is unmatched — he ran a 4.33 at the combine and benched 225 lbs 27 times.",
    stats: { Rec: 66, Yards: 992, TDs: 8 },
  },
  {
    id: "tyler-lockett",
    name: "Tyler Lockett",
    number: 16,
    position: "WR",
    depthRank: 1,
    status: "starter",
    age: 32,
    college: "Kansas State",
    experience: 10,
    height: "5'10\"",
    weight: 182,
    bio: "A Seahawks cornerstone and one of the most reliable receivers of his generation. Lockett's precise routes and elite hands have made him Geno's security blanket.",
    stats: { Rec: 59, Yards: 722, TDs: 6 },
  },
  {
    id: "jake-bobo",
    name: "Jake Bobo",
    number: 80,
    position: "WR",
    depthRank: 2,
    status: "backup",
    age: 25,
    college: "UCLA",
    experience: 2,
    height: "6'4\"",
    weight: 207,
    bio: "An oversized possession receiver with terrific hands. Bobo carved out a role as a reliable red-zone target as an undrafted free agent.",
  },
  {
    id: "laviska-shenault",
    name: "Laviska Shenault Jr.",
    number: 18,
    position: "WR",
    depthRank: 2,
    status: "backup",
    age: 26,
    college: "Colorado",
    experience: 5,
    height: "6'1\"",
    weight: 227,
    bio: "A physical, YAC-friendly receiver who also handles kick return duties. Provides snaps from the slot in jet motion packages.",
  },
  {
    id: "dareke-young",
    name: "Dareke Young",
    number: 88,
    position: "WR",
    depthRank: 3,
    status: "backup",
    age: 26,
    college: "Lenoir-Rhyne",
    experience: 3,
    height: "6'2\"",
    weight: 226,
    bio: "A core special teamer and reserve receiver. Earns his spot through blocking and gunner work.",
  },

  // TE
  {
    id: "noah-fant",
    name: "Noah Fant",
    number: 87,
    position: "TE",
    depthRank: 1,
    status: "starter",
    age: 27,
    college: "Iowa",
    experience: 6,
    height: "6'4\"",
    weight: 249,
    bio: "An athletic pass-catcher who adds a vertical dimension to Seattle's tight end usage. His speed after the catch makes him a mismatch against linebackers.",
    stats: { Rec: 44, Yards: 491, TDs: 3 },
  },
  {
    id: "aj-barner",
    name: "AJ Barner",
    number: 89,
    position: "TE",
    depthRank: 2,
    status: "backup",
    age: 23,
    college: "Michigan",
    experience: 2,
    height: "6'6\"",
    weight: 251,
    bio: "A traditional Y tight end with sneaky receiving production. Barner stepped up as a rookie and earned snaps in two-TE sets as the in-line blocker.",
  },
  {
    id: "pharaoh-brown",
    name: "Pharaoh Brown",
    number: 85,
    position: "TE",
    depthRank: 3,
    status: "backup",
    age: 31,
    college: "Oregon",
    experience: 7,
    height: "6'6\"",
    weight: 261,
    bio: "A heavy-bodied blocking tight end who provides muscle for the run game.",
  },

  // OL
  {
    id: "charles-cross",
    name: "Charles Cross",
    number: 67,
    position: "LT",
    depthRank: 1,
    status: "starter",
    age: 24,
    college: "Mississippi State",
    experience: 3,
    height: "6'5\"",
    weight: 310,
    bio: "The cornerstone of Seattle's rebuilt offensive line. Cross has established himself as one of the premier young left tackles in the NFL, protecting the blind side with technical precision.",
    stats: { "PFF Grade": 74.2, "Sacks Allowed": 3 },
  },
  {
    id: "stone-forsythe",
    name: "Stone Forsythe",
    number: 78,
    position: "LT",
    depthRank: 2,
    status: "backup",
    age: 27,
    college: "Florida",
    experience: 4,
    height: "6'8\"",
    weight: 307,
    bio: "Swing tackle who can fill in on either side. A valuable depth piece who's started in spot duty.",
  },
  {
    id: "laken-tomlinson",
    name: "Laken Tomlinson",
    number: 77,
    position: "LG",
    depthRank: 1,
    status: "starter",
    age: 33,
    college: "Duke",
    experience: 10,
    height: "6'3\"",
    weight: 330,
    bio: "A veteran presence providing stability at left guard. His experience and technique anchor the left side of Seattle's offensive line.",
  },
  {
    id: "phil-haynes",
    name: "Phil Haynes",
    number: 64,
    position: "LG",
    depthRank: 2,
    status: "backup",
    age: 29,
    college: "Wake Forest",
    experience: 6,
    height: "6'4\"",
    weight: 322,
    bio: "Interior reserve with experience at both guard spots. Provides position-flex when injuries hit the line.",
  },
  {
    id: "connor-williams",
    name: "Connor Williams",
    number: 52,
    position: "C",
    depthRank: 1,
    status: "starter",
    age: 28,
    college: "Texas",
    experience: 7,
    height: "6'4\"",
    weight: 302,
    bio: "A reliable center who directs Seattle's protection schemes. His communication skills at the line of scrimmage are a key part of the offense's success.",
  },
  {
    id: "olu-oluwatimi",
    name: "Olu Oluwatimi",
    number: 54,
    position: "C",
    depthRank: 2,
    status: "backup",
    age: 25,
    college: "Michigan",
    experience: 2,
    height: "6'3\"",
    weight: 309,
    bio: "Rimington Trophy winner developing behind Williams. The future of Seattle's center spot.",
  },
  {
    id: "anthony-bradford",
    name: "Anthony Bradford",
    number: 66,
    position: "RG",
    depthRank: 1,
    status: "starter",
    age: 25,
    college: "LSU",
    experience: 2,
    height: "6'4\"",
    weight: 345,
    bio: "A physically imposing guard who brings raw power to Seattle's right side. The 2023 fourth-round pick is developing into a solid starter.",
  },
  {
    id: "sataoa-laumea",
    name: "Sataoa Laumea",
    number: 74,
    position: "RG",
    depthRank: 2,
    status: "rookie",
    age: 23,
    college: "Utah",
    experience: 1,
    height: "6'4\"",
    weight: 315,
    bio: "A rookie interior lineman still developing but showing flashes of high-end potential. His run blocking has been a consistent bright spot.",
  },
  {
    id: "abe-lucas",
    name: "Abe Lucas",
    number: 72,
    position: "RT",
    depthRank: 1,
    status: "starter",
    age: 25,
    college: "Washington State",
    experience: 3,
    height: "6'6\"",
    weight: 316,
    bio: "A physical right tackle who excels in the run game. Lucas has steadily improved each season and is developing into a cornerstone of Seattle's line.",
  },
  {
    id: "mcclendon-curtis",
    name: "McClendon Curtis",
    number: 79,
    position: "RT",
    depthRank: 2,
    status: "backup",
    age: 25,
    college: "Chattanooga",
    experience: 2,
    height: "6'6\"",
    weight: 327,
    bio: "Developmental tackle with the frame to play either side. Project-level depth on the OL.",
  },

  // ───────── DEFENSE ─────────
  // DE
  {
    id: "uchenna-nwosu",
    name: "Uchenna Nwosu",
    number: 10,
    position: "DE",
    depthRank: 1,
    status: "starter",
    age: 28,
    college: "USC",
    experience: 6,
    height: "6'2\"",
    weight: 250,
    bio: "A versatile edge rusher who can set the edge and rush the passer. Nwosu's motor and relentless effort make him a disruptive force off the edge.",
    stats: { Sacks: 8.0, TFLs: 10 },
  },
  {
    id: "boye-mafe",
    name: "Boye Mafe",
    number: 53,
    position: "DE",
    depthRank: 1,
    status: "starter",
    age: 26,
    college: "Minnesota",
    experience: 3,
    height: "6'4\"",
    weight: 261,
    bio: "An ascending pass rusher with freakish athletic traits. Mafe is developing into a cornerstone of Seattle's defensive front with his combination of speed and power.",
    stats: { Sacks: 7.0 },
  },
  {
    id: "derick-hall",
    name: "Derick Hall",
    number: 58,
    position: "DE",
    depthRank: 2,
    status: "backup",
    age: 24,
    college: "Auburn",
    experience: 2,
    height: "6'3\"",
    weight: 254,
    bio: "Long-armed edge rusher continuing to develop his pass-rush plan. Earns rotational snaps as the 3rd edge.",
  },

  // DT
  {
    id: "leonard-williams",
    name: "Leonard Williams",
    number: 99,
    position: "DT",
    depthRank: 1,
    status: "starter",
    age: 30,
    college: "USC",
    experience: 10,
    height: "6'5\"",
    weight: 302,
    bio: "A dominant interior force signed in 2024. Williams brings veteran leadership and consistent disruption up the middle, demanding double-teams that free up Seattle's pass rushers.",
    stats: { Sacks: 6.5, TFLs: 12 },
  },
  {
    id: "jarran-reed",
    name: "Jarran Reed",
    number: 90,
    position: "DT",
    depthRank: 1,
    status: "starter",
    age: 31,
    college: "Alabama",
    experience: 8,
    height: "6'3\"",
    weight: 309,
    bio: "A savvy veteran returning to Seattle. Reed's first stint included a 10.5-sack season in 2018. He provides valuable depth and situational pass-rush ability.",
  },
  {
    id: "byron-murphy-ii",
    name: "Byron Murphy II",
    number: 91,
    position: "DT",
    depthRank: 2,
    status: "rookie",
    age: 22,
    college: "Texas",
    experience: 1,
    height: "6'1\"",
    weight: 308,
    bio: "Seattle's 2024 first-round pick. A disruptive interior penetrator with quickness off the snap. The future face of Seattle's defensive front.",
  },
  {
    id: "johnathan-hankins",
    name: "Johnathan Hankins",
    number: 94,
    position: "DT",
    depthRank: 3,
    status: "backup",
    age: 33,
    college: "Ohio State",
    experience: 12,
    height: "6'3\"",
    weight: 320,
    bio: "Veteran nose tackle providing run-stuffing snaps in early-down packages.",
  },

  // LB
  {
    id: "jerome-baker",
    name: "Jerome Baker",
    number: 17,
    position: "LB",
    depthRank: 1,
    status: "starter",
    age: 29,
    college: "Ohio State",
    experience: 7,
    height: "6'2\"",
    weight: 232,
    bio: "A rangy linebacker who excels in coverage. Baker's athleticism allows him to match up with tight ends and backs in space, giving Seattle flexibility in their defensive packages.",
    stats: { Tackles: 89, INT: 2 },
  },
  {
    id: "tyrel-dodson",
    name: "Tyrel Dodson",
    number: 51,
    position: "LB",
    depthRank: 1,
    status: "starter",
    age: 27,
    college: "Texas A&M",
    experience: 5,
    height: "6'1\"",
    weight: 240,
    bio: "A physical inside linebacker who fills gaps and stops the run. Dodson is the thumper in Seattle's linebacking corps, bringing aggression and toughness to the middle.",
    stats: { Tackles: 102, TFLs: 6 },
  },
  {
    id: "dre-greenlaw",
    name: "Dre Greenlaw",
    number: 57,
    position: "LB",
    depthRank: 1,
    status: "starter",
    age: 27,
    college: "Arkansas",
    experience: 5,
    height: "6'0\"",
    weight: 237,
    bio: "An instinctive linebacker who excels in run defense and zone coverage. His football IQ allows him to diagnose plays quickly and get in position before the snap.",
  },
  {
    id: "tyrice-knight",
    name: "Tyrice Knight",
    number: 48,
    position: "LB",
    depthRank: 2,
    status: "rookie",
    age: 23,
    college: "UTEP",
    experience: 1,
    height: "6'1\"",
    weight: 233,
    bio: "Day three pick with rare speed for the position. Earning early-down work and core special teams snaps.",
  },
  {
    id: "drake-thomas",
    name: "Drake Thomas",
    number: 43,
    position: "LB",
    depthRank: 3,
    status: "backup",
    age: 24,
    college: "NC State",
    experience: 2,
    height: "5'11\"",
    weight: 230,
    bio: "Undersized but instinctive backup linebacker and core special teamer.",
  },

  // CB
  {
    id: "devon-witherspoon",
    name: "Devon Witherspoon",
    number: 21,
    position: "CB",
    depthRank: 1,
    status: "starter",
    age: 24,
    college: "Illinois",
    experience: 2,
    height: "6'0\"",
    weight: 185,
    bio: "The 2023 fifth overall pick has emerged as one of the NFL's best young corners. His physical press coverage and ball-hawk instincts immediately evoke memories of Richard Sherman.",
    stats: { INTs: 3, PBUs: 12, "PFF Grade": 82.4 },
  },
  {
    id: "riq-woolen",
    name: "Riq Woolen",
    number: 27,
    position: "CB",
    depthRank: 1,
    status: "starter",
    age: 26,
    college: "UTSA",
    experience: 3,
    height: "6'4\"",
    weight: 205,
    bio: "A rare combination of elite size and elite speed (4.26 40-yard dash). Woolen led the NFL with 6 interceptions as a rookie, announcing himself as one of the game's most unique cornerbacks.",
    stats: { INTs: 4, PBUs: 8 },
  },
  {
    id: "coby-bryant",
    name: "Coby Bryant",
    number: 8,
    position: "CB",
    depthRank: 2,
    status: "backup",
    age: 25,
    college: "Cincinnati",
    experience: 3,
    height: "6'1\"",
    weight: 193,
    bio: "Versatile nickel corner who plays inside and outside. Brings ball skills and physicality to the slot.",
  },
  {
    id: "tre-brown",
    name: "Tre Brown",
    number: 22,
    position: "CB",
    depthRank: 2,
    status: "backup",
    age: 28,
    college: "Oklahoma",
    experience: 4,
    height: "5'10\"",
    weight: 188,
    bio: "Sticky cover corner with quickness in tight space. Reliable outside backup who starts when called upon.",
  },
  {
    id: "josh-jobe",
    name: "Josh Jobe",
    number: 30,
    position: "CB",
    depthRank: 3,
    status: "backup",
    age: 26,
    college: "Alabama",
    experience: 3,
    height: "6'0\"",
    weight: 187,
    bio: "Depth corner and core special teams contributor.",
  },

  // Safety
  {
    id: "quandre-diggs",
    name: "Quandre Diggs",
    number: 6,
    position: "S",
    depthRank: 1,
    status: "starter",
    age: 31,
    college: "Texas",
    experience: 10,
    height: "5'9\"",
    weight: 203,
    bio: "The heartbeat of Seattle's secondary. Diggs' exceptional football IQ and leadership have been a cornerstone of the Seahawks defense for years. A Pro Bowl selection multiple times.",
    stats: { INTs: 2, Tackles: 68 },
  },
  {
    id: "julian-love",
    name: "Julian Love",
    number: 37,
    position: "S",
    depthRank: 1,
    status: "starter",
    age: 27,
    college: "Notre Dame",
    experience: 6,
    height: "5'11\"",
    weight: 196,
    bio: "A versatile safety who can play in the box or deep. Love's range and instincts make him the last line of defense in Seattle's secondary, cleaning up mistakes and creating turnovers.",
    stats: { INTs: 3, Tackles: 74 },
  },
  {
    id: "rayshawn-jenkins",
    name: "Rayshawn Jenkins",
    number: 2,
    position: "S",
    depthRank: 2,
    status: "backup",
    age: 31,
    college: "Miami",
    experience: 8,
    height: "6'1\"",
    weight: 215,
    bio: "Veteran box safety with the size to play near the line. Provides experience and pop on contact.",
  },
  {
    id: "kvon-wallace",
    name: "K'Von Wallace",
    number: 29,
    position: "S",
    depthRank: 3,
    status: "backup",
    age: 27,
    college: "Clemson",
    experience: 5,
    height: "5'11\"",
    weight: 206,
    bio: "Reserve safety and special teams ace.",
  },

  // ───────── SPECIAL TEAMS ─────────
  {
    id: "jason-myers",
    name: "Jason Myers",
    number: 3,
    position: "K",
    depthRank: 1,
    status: "starter",
    age: 33,
    college: "Marist",
    experience: 10,
    height: "5'10\"",
    weight: 190,
    bio: "Dependable veteran kicker who won AFC Special Teams Player of the Year in 2018. Consistent and reliable from inside 50 yards.",
    stats: { "FG %": "88%", "XP Made": "26/26", Long: 61 },
  },
  {
    id: "michael-dickson",
    name: "Michael Dickson",
    number: 4,
    position: "P",
    depthRank: 1,
    status: "starter",
    age: 28,
    college: "Texas",
    experience: 7,
    height: "6'2\"",
    weight: 212,
    bio: "Widely considered one of the top punters in the NFL. Dickson's directional punting and hang time are elite, consistently flipping field position.",
    stats: { Avg: 48.2, "In 20": 31, Long: 67 },
  },
  {
    id: "chris-stoll",
    name: "Chris Stoll",
    number: 49,
    position: "LS",
    depthRank: 1,
    status: "starter",
    age: 26,
    college: "Penn State",
    experience: 2,
    height: "6'2\"",
    weight: 245,
    bio: "Reliable long snapper handling all field goals, extra points, and punts.",
  },
];

// Field layout coords: x = 0–100 (% across), y = 0–100 (% down).
// y=50 is the line of scrimmage. Defense y < 50, offense y > 50.

const OFFENSE_SLOTS: FieldSlot[] = [
  { id: "off-wr-l", playerId: "jaxon-smith-njigba", x: 8, y: 54, label: "WR" },
  { id: "off-wr-slot", playerId: "tyler-lockett", x: 22, y: 54, label: "WR" },
  { id: "off-te", playerId: "noah-fant", x: 78, y: 54, label: "TE" },
  { id: "off-wr-r", playerId: "dk-metcalf", x: 92, y: 54, label: "WR" },
  { id: "off-lt", playerId: "charles-cross", x: 25, y: 66, label: "LT" },
  { id: "off-lg", playerId: "laken-tomlinson", x: 37, y: 66, label: "LG" },
  { id: "off-c", playerId: "connor-williams", x: 50, y: 66, label: "C" },
  { id: "off-rg", playerId: "anthony-bradford", x: 63, y: 66, label: "RG" },
  { id: "off-rt", playerId: "abe-lucas", x: 75, y: 66, label: "RT" },
  { id: "off-qb", playerId: "geno-smith", x: 50, y: 78, label: "QB" },
  { id: "off-rb", playerId: "kenneth-walker", x: 50, y: 90, label: "RB" },
];

const DEFENSE_SLOTS: FieldSlot[] = [
  { id: "def-ss", playerId: "quandre-diggs", x: 34, y: 8, label: "SS" },
  { id: "def-fs", playerId: "julian-love", x: 66, y: 8, label: "FS" },
  { id: "def-cb-l", playerId: "devon-witherspoon", x: 8, y: 20, label: "CB" },
  { id: "def-cb-r", playerId: "riq-woolen", x: 92, y: 20, label: "CB" },
  { id: "def-lb-w", playerId: "dre-greenlaw", x: 24, y: 32, label: "WLB" },
  { id: "def-lb-m", playerId: "tyrel-dodson", x: 50, y: 32, label: "MLB" },
  { id: "def-lb-s", playerId: "jerome-baker", x: 76, y: 32, label: "SLB" },
  { id: "def-de-l", playerId: "uchenna-nwosu", x: 22, y: 44, label: "DE" },
  { id: "def-dt-l", playerId: "leonard-williams", x: 42, y: 44, label: "DT" },
  { id: "def-dt-r", playerId: "jarran-reed", x: 58, y: 44, label: "DT" },
  { id: "def-de-r", playerId: "boye-mafe", x: 78, y: 44, label: "DE" },
];

const SPECIAL_SLOTS: FieldSlot[] = [
  { id: "st-kr", playerId: "laviska-shenault", x: 30, y: 18, label: "KR" },
  { id: "st-pr", playerId: "jaxon-smith-njigba", x: 70, y: 18, label: "PR" },
  { id: "st-ls", playerId: "chris-stoll", x: 50, y: 68, label: "LS" },
  { id: "st-k", playerId: "jason-myers", x: 38, y: 80, label: "K" },
  { id: "st-p", playerId: "michael-dickson", x: 62, y: 80, label: "P" },
];

export const SEAHAWKS: TeamRoster = {
  team: {
    id: "seahawks",
    city: "Seattle",
    name: "Seahawks",
    abbrev: "SEA",
    conference: "NFC",
    division: "West",
    colors: {
      primary: "#002244",
      secondary: "#69BE28",
      accent: "#A5ACAF",
    },
  },
  players: PLAYERS,
  formations: {
    offense: OFFENSE_SLOTS,
    defense: DEFENSE_SLOTS,
    special: SPECIAL_SLOTS,
  },
};
