import type { Conference, Division } from '../types';
import { LEAGUE } from './league';

// Conference/division aren't in the registry seed (they come from ESPN standings at ingest
// time), but the teams table needs them non-null, so the local baseline supplies them here.
const TEAM_LOCATIONS: Record<string, { conference: Conference; division: Division }> = {
  bills: { conference: 'AFC', division: 'East' },
  dolphins: { conference: 'AFC', division: 'East' },
  patriots: { conference: 'AFC', division: 'East' },
  jets: { conference: 'AFC', division: 'East' },
  ravens: { conference: 'AFC', division: 'North' },
  bengals: { conference: 'AFC', division: 'North' },
  browns: { conference: 'AFC', division: 'North' },
  steelers: { conference: 'AFC', division: 'North' },
  colts: { conference: 'AFC', division: 'South' },
  jaguars: { conference: 'AFC', division: 'South' },
  texans: { conference: 'AFC', division: 'South' },
  titans: { conference: 'AFC', division: 'South' },
  broncos: { conference: 'AFC', division: 'West' },
  chargers: { conference: 'AFC', division: 'West' },
  chiefs: { conference: 'AFC', division: 'West' },
  raiders: { conference: 'AFC', division: 'West' },
  cowboys: { conference: 'NFC', division: 'East' },
  giants: { conference: 'NFC', division: 'East' },
  eagles: { conference: 'NFC', division: 'East' },
  commanders: { conference: 'NFC', division: 'East' },
  bears: { conference: 'NFC', division: 'North' },
  lions: { conference: 'NFC', division: 'North' },
  packers: { conference: 'NFC', division: 'North' },
  vikings: { conference: 'NFC', division: 'North' },
  falcons: { conference: 'NFC', division: 'South' },
  panthers: { conference: 'NFC', division: 'South' },
  saints: { conference: 'NFC', division: 'South' },
  buccaneers: { conference: 'NFC', division: 'South' },
  cardinals: { conference: 'NFC', division: 'West' },
  rams: { conference: 'NFC', division: 'West' },
  '49ers': { conference: 'NFC', division: 'West' },
  seahawks: { conference: 'NFC', division: 'West' },
};

function sqlStr(v: string): string {
  return `'${v.replace(/'/g, "''")}'`;
}

// Baseline team rows so a local `supabase db reset` has teams to reference BEFORE the
// FK-backed uniforms seed and the home-row backfill run. Colors come from the registry
// (lib/teams/league.ts) so local dev shows real colors without running the ESPN ingest.
//
// ON CONFLICT DO NOTHING is deliberate: in an already-populated database (prod, whose colors
// come from the weekly ESPN ingest) this seed is a no-op and never overwrites live data. It
// only fills an empty table.
export function generateTeamSeedSql(): string {
  const rows = LEAGUE.map((teamSeed) => {
    const team = teamSeed.team;
    const loc = TEAM_LOCATIONS[team.id];
    if (!loc) throw new Error(`team seed: no conference/division mapping for ${team.id}`);
    const c = team.colors;
    return `  (${[
      sqlStr(team.id),
      sqlStr(team.abbrev),
      sqlStr(team.city),
      sqlStr(team.name),
      sqlStr(loc.conference),
      sqlStr(loc.division),
      sqlStr(c.primary),
      sqlStr(c.secondary),
      sqlStr(c.accent),
      sqlStr(c.uiAccent),
      sqlStr(c.onAccent),
    ].join(', ')})`;
  }).join(',\n');

  return `-- AUTO-GENERATED by scripts/gen-team-seed.mts from lib/teams/league.ts.
-- Do not edit by hand. Baseline team rows for local dev (db reset) so FK-backed seeds and
-- the home-row backfill have teams to reference. ON CONFLICT DO NOTHING: a no-op in a
-- populated database (prod), never clobbering live ESPN-ingested colors.

insert into teams (
  id, abbrev, city, name, conference, division,
  color_primary, color_secondary, color_accent, ui_accent, on_accent
)
values
${rows}
on conflict (id) do nothing;
`;
}
