import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, it, expect } from 'vitest';
import { generateCuratedSeedSql } from '@/lib/uniforms/seed-sql';
import { uniformArtURL } from '@/lib/uniforms/art';
import { UNIFORMS } from '@/lib/uniforms/data';
import { LEGACY_ACCENTS } from '@/lib/uniforms/legacy-accents';

// The generated seed owns every uniform row. Stable IDs include the kit's start year so a
// later retirement changes dates/current-ness without renaming the row.

describe('uniform seed generator', () => {
  const sql = generateCuratedSeedSql();

  // ui_accent/on_accent are no longer on the archive rows — they come from the frozen
  // legacy map. Every emitted row must still carry its exact pair, because already-installed
  // iOS builds select those columns and decode them into non-optional Strings.
  it('emits each row with its frozen legacy accent pair', () => {
    for (const u of UNIFORMS) {
      const id = `${u.teamId}-${u.slug}-${u.yearStart}`;
      const pair = LEGACY_ACCENTS[id];
      const row = sql.split('\n').find((line) => line.includes(`('${id}',`));
      expect(row, `no emitted row for ${id}`).toBeDefined();
      expect(row).toContain(`'${pair.uiAccent}'`);
      expect(row).toContain(`'${pair.onAccent}'`);
    }
  });

  it('does not emit the removed source column', () => {
    expect(sql).not.toMatch(/\bsource\b/);
  });

  it('emits one row per curated kit, keyed by `${teamId}-${slug}-${yearStart}`', () => {
    for (const u of UNIFORMS) {
      expect(sql).toContain(`('${u.teamId}-${u.slug}-${u.yearStart}', '${u.teamId}',`);
    }
  });

  it("derives every row's image_path from its id (DEP-220 artifact URL)", () => {
    for (const u of UNIFORMS) {
      expect(sql).toContain(uniformArtURL(`${u.teamId}-${u.slug}-${u.yearStart}`));
    }
    // Every curated row must carry the path; a NULL image_path would leave the picker
    // without a thumbnail for a kit whose WebP is always generated. Paths are
    // origin-relative so web art resolves against the current request origin.
    const urls = (sql.match(/\/uniforms\/[a-z0-9-]+\.webp/g) ?? []).length;
    expect(urls).toBe(UNIFORMS.length);
  });

  // The committed reseed migration is the only path by which a catalog row reaches the
  // database, so a data.ts edit that ships without re-running gen-uniform-seed.mts leaves
  // the row invisible to the archive and the iOS picker while every other seed test still
  // passes. Pin the most recent generated migration to the generator's live output so the
  // omission fails here instead of in production.
  it('keeps the newest committed generated seed in sync with data.ts', () => {
    const migrationsDir = join(process.cwd(), 'supabase', 'migrations');
    const generatedSeed = readdirSync(migrationsDir)
      .filter((name) => name.endsWith('.sql'))
      .sort()
      .map((name) => ({ name, sql: readFileSync(join(migrationsDir, name), 'utf8') }))
      .filter(({ sql }) => sql.startsWith('-- AUTO-GENERATED by scripts/gen-uniform-seed.mts'))
      .pop();

    expect(generatedSeed, 'no generated uniform seed migration found').toBeDefined();
    expect(generateCuratedSeedSql()).toBe(generatedSeed?.sql);
  });
});
