import Foundation

/// Loads a cross-language fixture from web/fixtures/domain/<name>.json (the web app's
/// tree), the single source of truth generated by web/fixtures/generate.mts against the
/// TS oracle. Read directly from the repo path rather than a bundled copy — one file, no
/// regenerate-and-copy step to forget.
func loadFixture<T: Decodable>(_ name: String, as type: T.Type) throws -> T {
    let fileURL = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent() // FixtureLoading.swift -> DepthTests/
        .deletingLastPathComponent() // DepthTests/ -> repo root
        .appendingPathComponent("web/fixtures/domain/\(name).json")
    let data = try Data(contentsOf: fileURL)
    return try JSONDecoder().decode(T.self, from: data)
}
