import type { TeamCatalog } from '../core/catalog';

export const TEXANS_CATALOG: TeamCatalog = {
  teamId: 'texans',
  designs: [
    {
      slug: 'home',
      sleeveNike: 'white',
      name: 'Home',
      kind: 'home',
      jersey: 'navy',
      colors: { primary: '#03202F', secondary: '#A71930', accent: '#A71930' },
      legacyAccent: { uiAccent: '#5B9BFF', onAccent: '#0a0e1a' },
      periods: [{ from: 2024 }],
      combinations: [
        {
          key: 'standard',
          label: 'White pants',
          helmet: 'navy-bull',
          pants: 'white',
          pantsNike: 'navy',
          socks: 'navy',
        },
        {
          key: 'navy-pants',
          label: 'Navy pants',
          helmet: 'navy-bull',
          pants: 'navy',
          pantsNike: 'white',
          socks: 'navy',
        },
      ],
    },
    {
      slug: 'away',
      sleeveNike: 'navy',
      name: 'Away',
      kind: 'away',
      jersey: 'white',
      colors: { primary: '#FFFFFF', secondary: '#03202F', accent: '#A71930' },
      legacyAccent: { uiAccent: '#5B9BFF', onAccent: '#0a0e1a' },
      periods: [{ from: 2024 }],
      combinations: [
        {
          key: 'standard',
          label: 'Navy pants',
          helmet: 'navy-bull',
          pants: 'navy',
          pantsNike: 'white',
          socks: 'navy',
        },
        {
          key: 'white-pants',
          label: 'White pants',
          helmet: 'navy-bull',
          pants: 'white',
          pantsNike: 'navy',
          socks: 'white',
        },
      ],
    },
    {
      slug: 'battle-red',
      sleeveNike: 'white',
      name: 'Battle Red',
      kind: 'alternate',
      jersey: 'red',
      colors: { primary: '#A71930', secondary: '#03202F', accent: '#FFFFFF' },
      legacyAccent: { uiAccent: '#5B9BFF', onAccent: '#0a0e1a' },
      periods: [{ from: 2024 }],
      combinations: [
        {
          key: 'standard',
          label: 'Standard',
          helmet: 'red-horn',
          pants: 'red',
          pantsNike: 'white',
          socks: 'red',
        },
      ],
    },
    {
      slug: 'h-town',
      sleeveNike: 'hTownBlue',
      name: 'H-Town Blue',
      kind: 'alternate',
      jersey: 'h-town',
      colors: { primary: '#03202F', secondary: '#0072CE', accent: '#A71930' },
      legacyAccent: { uiAccent: '#5B9BFF', onAccent: '#0a0e1a' },
      periods: [{ from: 2024 }],
      combinations: [
        {
          key: 'standard',
          label: 'Standard',
          helmet: 'navy-h',
          pants: 'h-town',
          pantsNike: 'white',
          socks: 'navy',
        },
      ],
    },
  ],
};
