"""Bake Cooper's Tennessee-Titans-Logo.svg directly into the Titans decal (DEP-465).

Usage: python3 scripts/uniform-draw/titans_decal.py /path/to/Tennessee-Titans-Logo.svg
Preserve all 14 paths, their original colors and paint order; no trace or simplification.
GUD 2025 supplies placement only: shell approximately x65..154/y28..115,
flaming-T x78..121/y37..68. Transferring its left/top offsets and width to the
raw shell x139..702/y65..637 yields x218/y123/width276. Preserve source aspect,
with no rotation: the flame already rises toward the rear. Historical Oilers
art is a different mark and is not replaced by the supplied modern logo.
"""

import hashlib
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


def bake(element):
    # The supplied file uses only relative polygon commands and per-path translations.
    tx, *rest = map(float, re.findall(r'-?\d+(?:\.\d+)?', element.attrib['transform']))
    ty = rest[0] if rest else 0
    tokens = re.findall(r'[mlhvz]|-?\d+(?:\.\d+)?', element.attrib['d'])
    x = y = sx = sy = 0
    out = []
    i = 0
    command = None
    while i < len(tokens):
        if tokens[i].isalpha():
            command = tokens[i]
            i += 1
        if command == 'z':
            out.append('Z')
            x, y = sx, sy
            continue
        if command in ('m', 'l'):
            x += float(tokens[i])
            y += float(tokens[i + 1])
            i += 2
        elif command == 'h':
            x += float(tokens[i])
            i += 1
        elif command == 'v':
            y += float(tokens[i])
            i += 1
        else:
            raise ValueError(f'Unsupported command: {command}')
        move = command == 'm'
        if move:
            sx, sy = x, y
            command = 'l'
        # Source silhouette bounds x226..1840/y13..1139, fitted to the GUD placement box.
        px = 218 + (x + tx - 226) * 276 / 1614
        py = 123 + (y + ty - 13) * 276 / 1614
        out.append(f'{"M" if move else "L"}{px:.3f},{py:.3f}')
    return ' '.join(out)


source = Path(sys.argv[1]).read_bytes()
root = ET.fromstring(source)
target = Path(__file__).resolve().parents[2] / 'lib/uniforms/teams/titans.ts'
text = target.read_text()
start = text.index('// Provenance:')
end = text.index('// The shoulder yoke', start)
header = (
    '// Provenance: user-supplied Tennessee-Titans-Logo.svg (DEP-465), club trademark/non-free art.\n'
    f'// Source SHA-256: {hashlib.sha256(source).hexdigest()}\n'
    '// Direct vector paths and original colors; all 14 supplied paths are retained.\n'
    '// Placement only: https://www.gridiron-uniforms.com/GUD/controller/controller.php?'
    'action=teams-season&team_id=TEN&year=2025\n'
    '// Generated by scripts/uniform-draw/titans_decal.py; coordinates include placement.\n'
    'export const TITANS_DECAL_PATHS = [\n'
)
paths = ''.join(
    f"  {{ fill: '{element.attrib['fill']}', d: '{bake(element)}' }},\n"
    for element in root
)
target.write_text(text[:start] + header + paths + '] as const;\n\n' + text[end:])
