-- AUTO-GENERATED by scripts/gen-team-seed.mts from lib/teams/league.ts.
-- Do not edit by hand. Baseline team rows for local dev (db reset) so FK-backed seeds and
-- the home-row backfill have teams to reference. ON CONFLICT DO NOTHING: a no-op in a
-- populated database (prod), never clobbering live ESPN-ingested colors.

insert into teams (
  id, abbrev, city, name, conference, division,
  color_primary, color_secondary, color_accent, ui_accent, on_accent
)
values
  ('bills', 'BUF', 'Buffalo', 'Bills', 'AFC', 'East', '#00338D', '#C60C30', '#C60C30', '#5B9BFF', '#0a0e1a'),
  ('dolphins', 'MIA', 'Miami', 'Dolphins', 'AFC', 'East', '#008E97', '#FC4C02', '#FC4C02', '#2DD4D4', '#0a0e1a'),
  ('patriots', 'NE', 'New England', 'Patriots', 'AFC', 'East', '#002244', '#C60C30', '#B0B7BC', '#C8CDD6', '#0a0e1a'),
  ('jets', 'NYJ', 'New York', 'Jets', 'AFC', 'East', '#125740', '#FFFFFF', '#FFFFFF', '#4CC38A', '#0a0e1a'),
  ('ravens', 'BAL', 'Baltimore', 'Ravens', 'AFC', 'North', '#241773', '#000000', '#9E7C0C', '#9F8CFF', '#0a0e1a'),
  ('bengals', 'CIN', 'Cincinnati', 'Bengals', 'AFC', 'North', '#FB4F14', '#000000', '#000000', '#FF6A33', '#0a0e1a'),
  ('browns', 'CLE', 'Cleveland', 'Browns', 'AFC', 'North', '#311D00', '#FF3C00', '#FF3C00', '#FF6A33', '#0a0e1a'),
  ('steelers', 'PIT', 'Pittsburgh', 'Steelers', 'AFC', 'North', '#FFB612', '#101820', '#101820', '#FFB612', '#0a0e1a'),
  ('texans', 'HOU', 'Houston', 'Texans', 'AFC', 'South', '#03202F', '#A71930', '#A71930', '#5B9BFF', '#0a0e1a'),
  ('colts', 'IND', 'Indianapolis', 'Colts', 'AFC', 'South', '#002C5F', '#A2AAAD', '#A2AAAD', '#5B9BFF', '#0a0e1a'),
  ('jaguars', 'JAX', 'Jacksonville', 'Jaguars', 'AFC', 'South', '#006778', '#D7A22A', '#D7A22A', '#2DD4D4', '#0a0e1a'),
  ('titans', 'TEN', 'Tennessee', 'Titans', 'AFC', 'South', '#0C2340', '#4B92DB', '#4B92DB', '#5BA8E8', '#0a0e1a'),
  ('broncos', 'DEN', 'Denver', 'Broncos', 'AFC', 'West', '#FB4F14', '#002244', '#002244', '#FF6A33', '#0a0e1a'),
  ('chiefs', 'KC', 'Kansas City', 'Chiefs', 'AFC', 'West', '#E31837', '#FFB81C', '#FFB81C', '#FF4D5E', '#0a0e1a'),
  ('raiders', 'LV', 'Las Vegas', 'Raiders', 'AFC', 'West', '#000000', '#A5ACAF', '#A5ACAF', '#C8CDD6', '#0a0e1a'),
  ('chargers', 'LAC', 'Los Angeles', 'Chargers', 'AFC', 'West', '#0080C6', '#FFC20E', '#FFC20E', '#36A7E0', '#0a0e1a'),
  ('cowboys', 'DAL', 'Dallas', 'Cowboys', 'NFC', 'East', '#003594', '#869397', '#869397', '#5B9BFF', '#0a0e1a'),
  ('giants', 'NYG', 'New York', 'Giants', 'NFC', 'East', '#0B2265', '#A71930', '#A71930', '#5B9BFF', '#0a0e1a'),
  ('eagles', 'PHI', 'Philadelphia', 'Eagles', 'NFC', 'East', '#004C54', '#A5ACAF', '#A5ACAF', '#2FA3A3', '#0a0e1a'),
  ('commanders', 'WAS', 'Washington', 'Commanders', 'NFC', 'East', '#5A1414', '#FFB612', '#FFB612', '#FFB612', '#0a0e1a'),
  ('bears', 'CHI', 'Chicago', 'Bears', 'NFC', 'North', '#0B162A', '#C83803', '#C83803', '#FF6A33', '#0a0e1a'),
  ('lions', 'DET', 'Detroit', 'Lions', 'NFC', 'North', '#0076B6', '#B0B7BC', '#B0B7BC', '#36A7E0', '#0a0e1a'),
  ('packers', 'GB', 'Green Bay', 'Packers', 'NFC', 'North', '#203731', '#FFB612', '#FFB612', '#FFB612', '#0a0e1a'),
  ('vikings', 'MIN', 'Minnesota', 'Vikings', 'NFC', 'North', '#4F2683', '#FFC62F', '#FFC62F', '#FFC62F', '#0a0e1a'),
  ('falcons', 'ATL', 'Atlanta', 'Falcons', 'NFC', 'South', '#A71930', '#000000', '#000000', '#FF4D5E', '#0a0e1a'),
  ('panthers', 'CAR', 'Carolina', 'Panthers', 'NFC', 'South', '#0085CA', '#101820', '#101820', '#36A7E0', '#0a0e1a'),
  ('saints', 'NO', 'New Orleans', 'Saints', 'NFC', 'South', '#D3BC8D', '#101820', '#101820', '#E2CC9A', '#0a0e1a'),
  ('buccaneers', 'TB', 'Tampa Bay', 'Buccaneers', 'NFC', 'South', '#D50A0A', '#34302B', '#FF7900', '#FF4D4D', '#0a0e1a'),
  ('seahawks', 'SEA', 'Seattle', 'Seahawks', 'NFC', 'West', '#002244', '#69BE28', '#A5ACAF', '#69BE28', '#0a0e1a'),
  ('cardinals', 'ARI', 'Arizona', 'Cardinals', 'NFC', 'West', '#97233F', '#000000', '#FFB612', '#FF4D6A', '#0a0e1a'),
  ('rams', 'LAR', 'Los Angeles', 'Rams', 'NFC', 'West', '#003594', '#FFA300', '#FFA300', '#FFC20E', '#0a0e1a'),
  ('49ers', 'SF', 'San Francisco', '49ers', 'NFC', 'West', '#AA0000', '#B3995D', '#B3995D', '#FF4D4D', '#0a0e1a')
on conflict (id) do nothing;
