-- Curated head-coach history for the three seasons the stats page currently shows
-- (2023-2025 -- the window backfilled by 20260714120000_team_stats_multi_season.sql).
-- Hand-researched 2026-07-14 against Wikipedia's "List of current NFL head coaches"
-- (https://en.wikipedia.org/wiki/List_of_current_National_Football_League_head_coaches,
-- gives each current coach's hire year, which fixes the boundary between seasons) plus
-- each team's individual head-coaches list page and contemporaneous reporting (NFL.com,
-- ESPN, ProFootballReference) for coaches no longer with the team, cross-checked live in
-- a browser rather than trusted from a single summarized fetch. `coach_experience` is
-- seasons as that team's HC counting the given season. Where a team fired its coach
-- mid-season, the row credits whoever coached the *majority* of that season's games
-- (interim or otherwise) -- e.g. Bears 2024 stays Matt Eberflus (fired after game 12 of
-- 17), Jets 2024 and Saints 2024 go to the interim who finished the season (fired after
-- 5 and 8 games respectively). This is a judgment call, not an ESPN-verified fact like
-- the rest of the schema -- flagged here per invariant 9 provenance-scoping.
--
-- This table does not self-update: the next time the 3-season window rolls forward
-- (2026 becomes a "prior" season once its standings are final), a new migration must
-- append that season's row for all 32 teams the same way.
insert into team_coach_seasons (team_id, season, coach_name, coach_experience) values
  ('49ers', 2023, 'Kyle Shanahan', 7),
  ('49ers', 2024, 'Kyle Shanahan', 8),
  ('49ers', 2025, 'Kyle Shanahan', 9),
  ('bears', 2023, 'Matt Eberflus', 2),
  ('bears', 2024, 'Matt Eberflus', 3),
  ('bears', 2025, 'Ben Johnson', 1),
  ('bengals', 2023, 'Zac Taylor', 5),
  ('bengals', 2024, 'Zac Taylor', 6),
  ('bengals', 2025, 'Zac Taylor', 7),
  ('bills', 2023, 'Sean McDermott', 7),
  ('bills', 2024, 'Sean McDermott', 8),
  ('bills', 2025, 'Sean McDermott', 9),
  ('broncos', 2023, 'Sean Payton', 1),
  ('broncos', 2024, 'Sean Payton', 2),
  ('broncos', 2025, 'Sean Payton', 3),
  ('browns', 2023, 'Kevin Stefanski', 4),
  ('browns', 2024, 'Kevin Stefanski', 5),
  ('browns', 2025, 'Kevin Stefanski', 6),
  ('buccaneers', 2023, 'Todd Bowles', 2),
  ('buccaneers', 2024, 'Todd Bowles', 3),
  ('buccaneers', 2025, 'Todd Bowles', 4),
  ('cardinals', 2023, 'Jonathan Gannon', 1),
  ('cardinals', 2024, 'Jonathan Gannon', 2),
  ('cardinals', 2025, 'Jonathan Gannon', 3),
  ('chargers', 2023, 'Brandon Staley', 3),
  ('chargers', 2024, 'Jim Harbaugh', 1),
  ('chargers', 2025, 'Jim Harbaugh', 2),
  ('chiefs', 2023, 'Andy Reid', 11),
  ('chiefs', 2024, 'Andy Reid', 12),
  ('chiefs', 2025, 'Andy Reid', 13),
  ('colts', 2023, 'Shane Steichen', 1),
  ('colts', 2024, 'Shane Steichen', 2),
  ('colts', 2025, 'Shane Steichen', 3),
  ('commanders', 2023, 'Ron Rivera', 4),
  ('commanders', 2024, 'Dan Quinn', 1),
  ('commanders', 2025, 'Dan Quinn', 2),
  ('cowboys', 2023, 'Mike McCarthy', 4),
  ('cowboys', 2024, 'Mike McCarthy', 5),
  ('cowboys', 2025, 'Brian Schottenheimer', 1),
  ('dolphins', 2023, 'Mike McDaniel', 2),
  ('dolphins', 2024, 'Mike McDaniel', 3),
  ('dolphins', 2025, 'Mike McDaniel', 4),
  ('eagles', 2023, 'Nick Sirianni', 3),
  ('eagles', 2024, 'Nick Sirianni', 4),
  ('eagles', 2025, 'Nick Sirianni', 5),
  ('falcons', 2023, 'Arthur Smith', 3),
  ('falcons', 2024, 'Raheem Morris', 1),
  ('falcons', 2025, 'Raheem Morris', 2),
  ('giants', 2023, 'Brian Daboll', 2),
  ('giants', 2024, 'Brian Daboll', 3),
  ('giants', 2025, 'Brian Daboll', 4),
  ('jaguars', 2023, 'Doug Pederson', 2),
  ('jaguars', 2024, 'Doug Pederson', 3),
  ('jaguars', 2025, 'Liam Coen', 1),
  ('jets', 2023, 'Robert Saleh', 3),
  ('jets', 2024, 'Jeff Ulbrich', 1),
  ('jets', 2025, 'Aaron Glenn', 1),
  ('lions', 2023, 'Dan Campbell', 3),
  ('lions', 2024, 'Dan Campbell', 4),
  ('lions', 2025, 'Dan Campbell', 5),
  ('packers', 2023, 'Matt LaFleur', 5),
  ('packers', 2024, 'Matt LaFleur', 6),
  ('packers', 2025, 'Matt LaFleur', 7),
  ('panthers', 2023, 'Frank Reich', 1),
  ('panthers', 2024, 'Dave Canales', 1),
  ('panthers', 2025, 'Dave Canales', 2),
  ('patriots', 2023, 'Bill Belichick', 24),
  ('patriots', 2024, 'Jerod Mayo', 1),
  ('patriots', 2025, 'Mike Vrabel', 1),
  ('raiders', 2023, 'Antonio Pierce', 1),
  ('raiders', 2024, 'Antonio Pierce', 2),
  ('raiders', 2025, 'Pete Carroll', 1),
  ('rams', 2023, 'Sean McVay', 7),
  ('rams', 2024, 'Sean McVay', 8),
  ('rams', 2025, 'Sean McVay', 9),
  ('ravens', 2023, 'John Harbaugh', 16),
  ('ravens', 2024, 'John Harbaugh', 17),
  ('ravens', 2025, 'John Harbaugh', 18),
  ('saints', 2023, 'Dennis Allen', 2),
  ('saints', 2024, 'Darren Rizzi', 1),
  ('saints', 2025, 'Kellen Moore', 1),
  ('seahawks', 2023, 'Pete Carroll', 14),
  ('seahawks', 2024, 'Mike Macdonald', 1),
  ('seahawks', 2025, 'Mike Macdonald', 2),
  ('steelers', 2023, 'Mike Tomlin', 17),
  ('steelers', 2024, 'Mike Tomlin', 18),
  ('steelers', 2025, 'Mike Tomlin', 19),
  ('texans', 2023, 'DeMeco Ryans', 1),
  ('texans', 2024, 'DeMeco Ryans', 2),
  ('texans', 2025, 'DeMeco Ryans', 3),
  ('titans', 2023, 'Mike Vrabel', 6),
  ('titans', 2024, 'Brian Callahan', 1),
  ('titans', 2025, 'Brian Callahan', 2),
  ('vikings', 2023, 'Kevin O''Connell', 2),
  ('vikings', 2024, 'Kevin O''Connell', 3),
  ('vikings', 2025, 'Kevin O''Connell', 4)
on conflict (team_id, season) do update set
  coach_name = excluded.coach_name,
  coach_experience = excluded.coach_experience,
  updated_at = now()
where team_coach_seasons.source = 'curated';
